<a href="https://colab.research.google.com/github/RuthlessActuary2023/CAS-RPM-2025-Python-Workshop/blob/main/2025_CAS_RPM_Python_Lesson_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lesson 2: Importing, Manipulating, and Analyzing Data

### Import pandas and name pd
### Set file path and name files
### Import .csv files with data

In [ ]:
# Code to clone the github repo into colab
!pip install gitpython
import git
import os

repo_url = 'https://github.com/RuthlessActuary2023/CAS-RPM-2025-Python-Workshop.git'
repo_dir = '/content/your-repo'

# Clone if it doesnâ€™t already exist
if not os.path.exists(repo_dir):
    git.Repo.clone_from(repo_url, repo_dir)

Requirement already satisfied: gitpython in /usr/local/lib/python3.11/dist-packages (3.1.44)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.11/dist-packages (from gitpython) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.11/dist-packages (from gitdb<5,>=4.0.1->gitpython) (5.0.2)

In [ ]:
import pandas as pd

data1 = pd.read_feather(repo_dir + '/base_data_for_intro_python.ftr')
cfax = pd.read_feather(repo_dir + '/carfax_fields_for_merge.ftr')
geo = pd.read_feather(repo_dir + '/geo_12312019.ftr')

### Look at shape of the data -> (rows, columns)

In [ ]:
print(data1.shape)
print(cfax.shape)
print(geo.shape)

(100443, 35)
(98566, 55)
(32364, 128)

### Use .head() to look at top 5 rows of data.

In [ ]:
data1.head()

,insstate,cbistier,vehuse,numveh,numdrv,modlyr,make,model,collsymb,perslimbi,...,cc_col,color_exterior,color_interior,year_CEF,mDrvGenMarSts,modelyear,rand,zip,pol_id,vin_id
0,OH,3,P,1,1.0,2010.0,NaN,NaN,12.0,50000.0,...,0,None,None,2010.0,MS,2010.0,0.012621,45424.0,0,0
1,OH,3,P,1,1.0,2010.0,NaN,NaN,12.0,50000.0,...,0,None,None,2010.0,MS,2010.0,0.012621,45424.0,0,0
2,OH,4,P,1,1.0,2010.0,NaN,NaN,12.0,50000.0,...,0,None,None,NaN,MS,2010.0,0.012621,45424.0,0,0
3,OH,3,P,1,1.0,2010.0,NaN,NaN,12.0,50000.0,...,0,None,None,2010.0,MS,2010.0,0.012621,45424.0,0,0
4,OH,4,P,1,1.0,2007.0,NaN,NaN,12.0,50000.0,...,0,None,None,2007.0,MS,2007.0,0.012621,45424.0,0,1

### Use .head(50) to look at first 50 records.

In [ ]:
data1.head(50)

,insstate,cbistier,vehuse,numveh,numdrv,modlyr,make,model,collsymb,perslimbi,...,cc_col,color_exterior,color_interior,year_CEF,mDrvGenMarSts,modelyear,rand,zip,pol_id,vin_id
0,OH,3,P,1,1.0,2010.0,NaN,NaN,12.0,50000.0,...,0,None,None,2010.0,MS,2010.0,0.012621,45424.0,0,0
1,OH,3,P,1,1.0,2010.0,NaN,NaN,12.0,50000.0,...,0,None,None,2010.0,MS,2010.0,0.012621,45424.0,0,0
2,OH,4,P,1,1.0,2010.0,NaN,NaN,12.0,50000.0,...,0,None,None,NaN,MS,2010.0,0.012621,45424.0,0,0
3,OH,3,P,1,1.0,2010.0,NaN,NaN,12.0,50000.0,...,0,None,None,2010.0,MS,2010.0,0.012621,45424.0,0,0
4,OH,4,P,1,1.0,2007.0,NaN,NaN,12.0,50000.0,...,0,None,None,2007.0,MS,2007.0,0.012621,45424.0,0,1
5,OH,7,W,1,1.0,2013.0,NaN,NaN,32.0,25000.0,...,0,None,None,NaN,FS,2013.0,0.013990,45424.0,1,2
6,OH,4,W,1,1.0,2006.0,NaN,NaN,15.0,100000.0,...,0,None,None,2006.0,MS,2006.0,0.005431,45424.0,2,3
7,OH,4,W,2,1.0,2006.0,NaN,NaN,15.0,100000.0,...,0,None,None,2006.0,MS,2006.0,0.005431,45424.0,2,3
8,OH,4,W,1,1.0,2006.0,NaN,NaN,15.0,100000.0,...,0,None,None,2006.0,MS,2006.0,0.005431,45424.0,2,3
9,OH,4,P,2,1.0,2014.0,NaN,NaN,54.0,100000.0,...,0,WHITE,BLACK,2014.0,MS,2014.0,0.005431,45424.0,2,4
10,OH,9,C,1,1.0,NaN,NaN,NaN,26.0,100000.0,...,0,BLACK,RED,2014.0,FS,2014.0,0.009414,45424.0,3,5
11,OH,9,C,1,1.0,NaN,NaN,NaN,26.0,100000.0,...,0,BLACK,RED,2014.0,FS,2014.0,0.009414,45424.0,3,5
12,OH,10,C,1,1.0,NaN,NaN,NaN,26.0,100000.0,...,0,BLACK,RED,2014.0,FS,2014.0,0.009414,45424.0,3,5
13,OH,9,C,1,1.0,NaN,NaN,NaN,26.0,100000.0,...,0,BLACK,RED,2014.0,FS,2014.0,0.009414,45424.0,3,5
14,OH,10,C,1,1.0,NaN,NaN,NaN,26.0,100000.0,...,0,BLACK,RED,2014.0,FS,2014.0,0.009414,45424.0,3,5
15,OH,9,C,1,1.0,NaN,NaN,NaN,26.0,100000.0,...,0,BLACK,RED,2014.0,FS,2014.0,0.009414,45424.0,3,5
16,OH,9,C,1,1.0,NaN,NaN,NaN,14.0,100000.0,...,0,None,None,2006.0,FS,2006.0,0.009414,45424.0,3,6
17,OH,10,C,1,1.0,NaN,NaN,NaN,14.0,100000.0,...,0,None,None,2006.0,FS,2006.0,0.009414,45424.0,3,6
18,OH,3,C,1,1.0,NaN,NaN,NaN,14.0,100000.0,...,0,None,None,2006.0,FS,2006.0,0.009414,45424.0,3,6
19,OH,10,C,1,1.0,NaN,NaN,NaN,14.0,100000.0,...,0,None,None,2006.0,FS,2006.0,0.009414,45424.0,3,6
20,OH,3,C,1,1.0,NaN,NaN,NaN,14.0,100000.0,...,0,None,None,2006.0,FS,2006.0,0.009414,45424.0,3,6
21,OH,6,P,2,2.0,NaN,NaN,NaN,14.0,25000.0,...,0,None,None,2008.0,FS,2008.0,0.021215,45424.0,4,7
22,OH,6,P,2,2.0,NaN,NaN,NaN,14.0,25000.0,...,0,None,None,2008.0,FS,2008.0,0.021215,45424.0,4,7
23,OH,6,P,2,2.0,NaN,NaN,NaN,15.0,25000.0,...,0,None,None,2007.0,MS,2007.0,0.021215,45424.0,4,8
24,OH,4,P,3,2.0,NaN,NaN,NaN,58.0,250000.0,...,0,GRAY,BLACK,2011.0,MM,2011.0,0.004235,45424.0,5,9
25,OH,5,P,3,2.0,NaN,NaN,NaN,58.0,250000.0,...,0,GRAY,BLACK,2011.0,FM,2011.0,0.004235,45424.0,5,9
26,OH,5,P,2,2.0,NaN,NaN,NaN,58.0,250000.0,...,0,GRAY,BLACK,2011.0,MM,2011.0,0.004235,45430.0,5,9
27,OH,5,P,2,2.0,NaN,NaN,NaN,14.0,250000.0,...,0,None,None,2009.0,MM,2009.0,0.004235,45424.0,5,10
28,OH,5,P,3,2.0,NaN,NaN,NaN,14.0,250000.0,...,1,None,None,2009.0,MM,2009.0,0.004235,45424.0,5,10
29,OH,5,P,2,2.0,NaN,NaN,NaN,14.0,250000.0,...,0,None,None,2009.0,MM,2009.0,0.004235,45430.0,5,10
30,OH,5,P,2,2.0,NaN,NaN,NaN,14.0,250000.0,...,0,None,None,2009.0,MM,2009.0,0.004235,45430.0,5,10
31,OH,7,P,2,2.0,NaN,NaN,NaN,14.0,250000.0,...,0,None,None,2009.0,MM,2009.0,0.004235,45430.0,5,10
32,OH,7,P,2,2.0,NaN,NaN,NaN,14.0,250000.0,...,0,None,None,2009.0,FM,2009.0,0.004235,45430.0,5,10
33,OH,3,P,2,2.0,NaN,NaN,NaN,14.0,250000.0,...,0,None,None,2009.0,FM,2009.0,0.004235,45430.0,5,10
34,OH,3,P,2,2.0,NaN,NaN,NaN,14.0,250000.0,...,0,None,None,2009.0,FM,2009.0,0.004235,45430.0,5,10
35,OH,4,C,3,2.0,NaN,NaN,NaN,41.0,250000.0,...,0,BLACK,GOLD,2015.0,MM,2015.0,0.004235,45424.0,5,11
36,OH,5,P,3,2.0,NaN,NaN,NaN,37.0,250000.0,...,0,BLACK,BLACK,2015.0,MM,2015.0,0.004235,45424.0,5,12
37,OH,4,P,3,2.0,NaN,NaN,NaN,35.0,250000.0,...,1,BLACK,BLACK,2015.0,FM,2015.0,0.004235,45424.0,5,12
38,OH,5,P,2,2.0,NaN,NaN,NaN,33.0,250000.0,...,0,GRAY,BLACK,2014.0,FM,2014.0,0.004235,45430.0,5,14003
39,OH,5,P,2,2.0,NaN,NaN,NaN,35.0,250000.0,...,0,GRAY,BLACK,2014.0,FM,2014.0,0.004235,45430.0,5,14003
40,OH,7,P,2,2.0,NaN,NaN,NaN,33.0,250000.0,...,0,GRAY,BLACK,2014.0,MM,2014.0,0.004235,45430.0,5,14003
41,OH,3,P,2,2.0,NaN,NaN,NaN,35.0,250000.0,...,0,GRAY,BLACK,2014.0,MM,2014.0,0.004235,45430.0,5,14003
42,OH,5,P,2,2.0,NaN,NaN,NaN,35.0,250000.0,...,0,GRAY,BLACK,2014.0,FM,2014.0,0.004235,45430.0,5,14003
43,OH,7,P,2,2.0,NaN,NaN,NaN,33.0,250000.0,...,0,GRAY,BLACK,2014.0,FM,2014.0,0.004235,45430.0,5,14003
44,OH,3,P,2,2.0,NaN,NaN,NaN,35.0,250000.0,...,0,GRAY,BLACK,2014.0,MM,2014.0,0.004235,45430.0,5,14003
45,OH,3,P,3,2.0,NaN,NaN,NaN,7.0,100000.0,...,0,None,None,2008.0,FM,2008.0,0.001345,45424.0,6,13
46,OH,3,P,2,2.0,NaN,NaN,NaN,7.0,100000.0,...,0,None,None,2008.0,FM,2008.0,0.001345,45424.0,6,13
47,OH,3,P,3,2.0,NaN,NaN,NaN,7.0,100000.0,...,0,None,None,2008.0,FM,2008.0,0.001345,45459.0,6,13
48,OH,3,C,3,2.0,NaN,NaN,NaN,13.0,100000.0,...,0,None,None,2004.0,MM,2004.0,0.001345,45424.0,6,14
49,OH,3,C,3,2.0,NaN,NaN,NaN,13.0,100000.0,...,0,None,None,2004.0,MM,2004.0,0.001345,45424.0,6,14

### Determine count of rows with null value for each field in dataset

In [ ]:
data1.isna().sum()

insstate               0
cbistier               0
vehuse               189
numveh                 0
numdrv                76
modlyr             83737
make              100443
model             100443
collsymb              14
perslimbi             17
acclimbi               1
deductiblecol       1570
pol_eff_date           0
pol_exp_date           0
pol_eff_year           0
DrvAge                60
DrvSex                62
DrvMarSts             60
ep_bi                  0
ep_col                 0
ee_bi                  0
ee_col                 0
incloss_bi             0
incloss_col            0
cc_bi                  0
cc_col                 0
color_exterior     56463
color_interior     54321
year_CEF            3068
mDrvGenMarSts       4482
modelyear           1283
rand                   0
zip                    0
pol_id                 0
vin_id                 0
dtype: int64

### Review datatypes
#### For more information about datatypes in python, this website is useful: https://www.geeksforgeeks.org/python-data-types/

In [ ]:
data1.dtypes

insstate           object
cbistier            int64
vehuse             object
numveh              int64
numdrv            float64
modlyr            float64
make              float64
model             float64
collsymb          float64
perslimbi         float64
acclimbi          float64
deductiblecol     float64
pol_eff_date       object
pol_exp_date       object
pol_eff_year        int64
DrvAge            float64
DrvSex             object
DrvMarSts          object
ep_bi             float64
ep_col            float64
ee_bi             float64
ee_col            float64
incloss_bi        float64
incloss_col       float64
cc_bi               int64
cc_col              int64
color_exterior     object
color_interior     object
year_CEF          float64
mDrvGenMarSts      object
modelyear         float64
rand              float64
zip               float64
pol_id              int64
vin_id              int64
dtype: object

### Switch datatype of pol_eff_date from object to a date
### Show a random sample of 25 of just the pol_eff_date column using [([])]

In [ ]:
data1['pol_eff_date'] = pd.to_datetime(data1['pol_eff_date'], infer_datetime_format = True)

data1[(['pol_eff_date'])].sample(n = 25)

<ipython-input-8-37731efda006>:1: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  data1['pol_eff_date'] = pd.to_datetime(data1['pol_eff_date'], infer_datetime_format = True)

      pol_eff_date
42170   2017-11-03
22949   2015-12-11
7742    2017-08-25
14727   2015-12-26
90332   2017-09-23
81797   2019-04-24
71558   2016-04-17
61147   2019-01-28
78737   2015-10-13
16213   2016-07-15
54889   2015-06-22
98142   2018-12-18
27378   2017-07-22
29466   2016-11-22
86443   2019-02-18
14701   2018-08-01
89701   2019-02-28
7351    2016-06-16
89562   2018-07-12
33759   2017-12-03
30030   2016-05-02
46034   2017-11-19
6156    2018-02-06
21568   2019-08-06
10401   2017-02-24

# View min, mean, max of all numeric variables and export to clipboard for excel

### Import numpy
### Identify the datatypes for each field by creating a dataframe with field name and dtype

In [ ]:
import numpy as np

a = data1.dtypes.reset_index()

a.head()

      index        0
0  insstate   object
1  cbistier    int64
2    vehuse   object
3    numveh    int64
4    numdrv  float64

### Rename the columns

In [ ]:
a.rename(columns = {'index': 'field', 0: 'dtype'}, inplace = True)

a.head()

      field    dtype
0  insstate   object
1  cbistier    int64
2    vehuse   object
3    numveh    int64
4    numdrv  float64

### Filter using .loc to only those which are not strings and make a new df as a copy
#### Helpful Hint: Creating a copy of a df is usually done to avoid errors later

In [ ]:
numerics = a.loc[a['dtype'] != 'object'].copy()

numerics.head()

      field    dtype
1  cbistier    int64
3    numveh    int64
4    numdrv  float64
5    modlyr  float64
6      make  float64

### As a quick check, use groupby to see the dtypes and count

In [ ]:
numerics.groupby(['dtype']).count().reset_index()

            dtype  field
0           int64      7
1         float64     19
2  datetime64[ns]      1

### Remove the dtype column by using .drop()
### Create columns for min, mean, and max by looping through a defined list and inserting NaN for all values to start

In [ ]:
numerics.drop(columns = 'dtype', inplace = True)

fields = ['min','mean','max']
for f in fields:
    numerics[f] = np.nan

numerics

            field  min  mean  max
1        cbistier  NaN   NaN  NaN
3          numveh  NaN   NaN  NaN
4          numdrv  NaN   NaN  NaN
5          modlyr  NaN   NaN  NaN
6            make  NaN   NaN  NaN
7           model  NaN   NaN  NaN
8        collsymb  NaN   NaN  NaN
9       perslimbi  NaN   NaN  NaN
10       acclimbi  NaN   NaN  NaN
11  deductiblecol  NaN   NaN  NaN
12   pol_eff_date  NaN   NaN  NaN
14   pol_eff_year  NaN   NaN  NaN
15         DrvAge  NaN   NaN  NaN
18          ep_bi  NaN   NaN  NaN
19         ep_col  NaN   NaN  NaN
20          ee_bi  NaN   NaN  NaN
21         ee_col  NaN   NaN  NaN
22     incloss_bi  NaN   NaN  NaN
23    incloss_col  NaN   NaN  NaN
24          cc_bi  NaN   NaN  NaN
25         cc_col  NaN   NaN  NaN
28       year_CEF  NaN   NaN  NaN
30      modelyear  NaN   NaN  NaN
31           rand  NaN   NaN  NaN
32            zip  NaN   NaN  NaN
33         pol_id  NaN   NaN  NaN
34         vin_id  NaN   NaN  NaN

### Create a list of all values in numerics['field'] using .to_list()

In [ ]:
numerics_list = numerics['field'].to_list()

numerics_list

['cbistier',
 'numveh',
 'numdrv',
 'modlyr',
 'make',
 'model',
 'collsymb',
 'perslimbi',
 'acclimbi',
 'deductiblecol',
 'pol_eff_date',
 'pol_eff_year',
 'DrvAge',
 'ep_bi',
 'ep_col',
 'ee_bi',
 'ee_col',
 'incloss_bi',
 'incloss_col',
 'cc_bi',
 'cc_col',
 'year_CEF',
 'modelyear',
 'rand',
 'zip',
 'pol_id',
 'vin_id']

### Loop over rows and columns to populate the table
#### Helpful Hint: You can produce a loop within a loop when you want to loop through multiple lists

In [ ]:
numerics_list = numerics['field'].to_list()

for n in numerics_list:
    for f in fields:
        nxt = numerics['field'] == n
        if f == 'min':
            numerics.loc[nxt,f] = data1[n].min()
        if f == 'mean':
            numerics.loc[nxt,f] = data1[n].mean()
        if f == 'max':
            numerics.loc[nxt,f] = data1[n].max()

numerics

<ipython-input-15-ac45a181a7e1>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2014-01-01 00:00:00' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  numerics.loc[nxt,f] = data1[n].min()
<ipython-input-15-ac45a181a7e1>:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2017-04-09 12:49:02.277709824' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  numerics.loc[nxt,f] = data1[n].mean()
<ipython-input-15-ac45a181a7e1>:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2019-12-31 00:00:00' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  numerics.loc[nxt,f] = data1[n].max()

,field,min,mean,max
1,cbistier,0.0,5.23693,99.0
3,numveh,1.0,2.428064,12.0
4,numdrv,1.0,2.132474,13.0
5,modlyr,1949.0,2008.523524,2019.0
6,make,NaN,NaN,NaN
7,model,NaN,NaN,NaN
8,collsymb,0.0,19.699629,75.0
9,perslimbi,25000.0,153700.784657,1000000.0
10,acclimbi,50000.0,321404.492145,1000000.0
11,deductiblecol,50.0,476.783854,5000.0
12,pol_eff_date,2014-01-01 00:00:00,2017-04-09 12:49:02.277709824,2019-12-31 00:00:00
14,pol_eff_year,2014,2016.780921,2019
15,DrvAge,0.0,51.298457,99.0
18,ep_bi,-7.0,97.772343,3074.56
19,ep_col,-0.0748,160.20454,6615.0
20,ee_bi,0.002732,0.562488,1.09589
21,ee_col,0.002732,0.562488,1.09589
22,incloss_bi,0.0,56.068848,496636.6
23,incloss_col,-750.04,77.66921,205193.28
24,cc_bi,0,0.003315,6
25,cc_col,0,0.020808,8
28,year_CEF,1981.0,2009.624924,2021.0
30,modelyear,1949.0,2009.600272,2021.0
31,rand,0.0,0.011206,0.022248
32,zip,43001.0,44277.382107,45898.0
33,pol_id,0,8005.572802,15910
34,vin_id,0,17340.137063,34524

### Copy to clipboard using .to_clipboard and view in Excel

In [ ]:
# numerics.to_clipboard(excel = True, index = False) # does not work in colab, keep here for reference

# Create function for analyzing data

### Use .groupby() and .agg to view some data in data1

In [ ]:
data1.groupby(['cbistier']).agg({'ee_bi': 'sum'}).reset_index()

    cbistier        ee_bi
0          0   649.130055
1          1  5860.327075
2          2  6993.019972
3          3  6648.480358
4          4  6190.745894
5          5  6235.280148
6          6  5920.227068
7          7  5706.139150
8          8  5037.354465
9          9  4160.333296
10        10  2911.364578
11        90   117.191377
12        99    68.390995

### Create pct_of_tot field

In [ ]:
a = data1.groupby(['cbistier']).agg({'ee_bi': 'sum'}).reset_index()
a['pct_of_tot'] = a['ee_bi']/a['ee_bi'].sum()
a

    cbistier        ee_bi  pct_of_tot
0          0   649.130055    0.011489
1          1  5860.327075    0.103726
2          2  6993.019972    0.123775
3          3  6648.480358    0.117676
4          4  6190.745894    0.109575
5          5  6235.280148    0.110363
6          6  5920.227068    0.104787
7          7  5706.139150    0.100997
8          8  5037.354465    0.089160
9          9  4160.333296    0.073637
10        10  2911.364578    0.051530
11        90   117.191377    0.002074
12        99    68.390995    0.001211

### Create a list comprehension to find the metrics we need
#### Helpful Hint: List comprehension is a good way to create lists
#### [expression for item in iterable if condition]

In [ ]:
facts = [i for i in data1.columns if 'ee_' in i or 'ep_' in i or 'incloss_' in i or 'cc_' in i]
facts

['ep_bi',
 'ep_col',
 'ee_bi',
 'ee_col',
 'incloss_bi',
 'incloss_col',
 'cc_bi',
 'cc_col']

### Define agg_dict
### Create a function eda_table0 that loops through the facts list and produces a table of aggregated data.

In [ ]:
agg_dict = {i: 'sum' for i in facts}

def eda_table0(data,field):
    a = data.groupby([field], dropna = False).agg(agg_dict).reset_index()

    for f in facts:
        a[f + '_pct'] = a[f]/a[f].sum()

    return a

### Set Display Settings to determine the number of columns and rows viewed and the size of the display.

### Run eda_table0 function on data1 dataset for cbistier

In [ ]:
pd.set_option("display.max_columns",25)
pd.set_option("display.max_rows",250)
pd.options.display.float_format = '{:,.2f}'.format

from IPython.display import display, HTML

display(HTML(data="""
<style>
    div#notebook-container    { width: 90%; }
    div#menubar-container     { width: 65%; }
    div#maintoolbar-container { width: 99%; }
</style>
"""))

eda_table0(data1,'cbistier')

,cbistier,ep_bi,ep_col,ee_bi,ee_col,incloss_bi,incloss_col,cc_bi,cc_col,ep_bi_pct,ep_col_pct,ee_bi_pct,ee_col_pct,incloss_bi_pct,incloss_col_pct,cc_bi_pct,cc_col_pct
0,0,"116,195.14","186,000.97",649.13,649.13,"33,097.00","82,796.27",3,26,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
1,1,"845,094.50","1,324,559.47","5,860.33","5,860.33","938,001.18","431,678.75",24,153,0.09,0.08,0.10,0.10,0.17,0.06,0.07,0.07
2,2,"985,485.00","1,555,607.09","6,993.02","6,993.02","275,257.88","470,211.01",20,189,0.10,0.10,0.12,0.12,0.05,0.06,0.06,0.09
3,3,"1,024,569.80","1,620,210.56","6,648.48","6,648.48","558,796.93","696,109.11",33,190,0.10,0.10,0.12,0.12,0.10,0.09,0.10,0.09
4,4,"1,045,432.40","1,635,138.07","6,190.75","6,190.75","504,033.64","854,050.04",38,215,0.11,0.10,0.11,0.11,0.09,0.11,0.11,0.10
5,5,"1,055,598.13","1,704,023.27","6,235.28","6,235.28","436,522.38","715,376.41",36,220,0.11,0.11,0.11,0.11,0.08,0.09,0.11,0.11
6,6,"1,050,536.31","1,736,862.38","5,920.23","5,920.23","741,131.17","873,603.34",33,221,0.11,0.11,0.10,0.10,0.13,0.11,0.10,0.11
7,7,"1,077,200.44","1,792,036.45","5,706.14","5,706.14","295,590.25","879,073.32",38,238,0.11,0.11,0.10,0.10,0.05,0.11,0.11,0.11
8,8,"1,004,587.53","1,695,278.16","5,037.35","5,037.35","454,016.81","879,640.76",40,225,0.10,0.11,0.09,0.09,0.08,0.11,0.12,0.11
9,9,"911,828.95","1,542,546.59","4,160.33","4,160.33","1,084,569.27","1,300,172.28",47,243,0.09,0.10,0.07,0.07,0.19,0.17,0.14,0.12
10,10,"665,502.61","1,233,799.63","2,911.36","2,911.36","310,706.76","576,572.10",21,161,0.07,0.08,0.05,0.05,0.06,0.07,0.06,0.08
11,90,"25,228.00","45,518.75",117.19,117.19,0.00,"35,049.52",0,6,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
12,99,"13,288.61","19,843.24",68.39,68.39,0.00,"6,995.60",0,3,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

### Create a more specific function, eda_table

In [ ]:
facts = [i for i in data1.columns if 'ee_' in i or 'ep_' in i or 'incloss_' in i or 'cc_' in i]
ee_list = [i for i in data1.columns if 'ee_' in i]
agg_dict = {i: 'sum' for i in facts}

covs = ['bi','col']

def eda_table(data,field):
    a = data.groupby([field], dropna = False).agg(agg_dict).reset_index()

    for e in ee_list:
        a[e + '_pct'] = a[e]/a[e].sum()

    for c in covs:
        a['avg_prem_' + c] = a['ep_' + c]/a['ee_' + c]
        a['lr_' + c] = a['incloss_' + c]/a['ep_' + c]
        a['freq_' + c] = a['cc_' + c]/a['ee_' + c]
        a['sev_' + c] = a['incloss_' + c]/a['cc_' + c]
        a['pp_' + c] = a['incloss_' + c]/a['ee_' + c]

    a.drop(columns = facts, inplace = True)
#     a = a.drop(columns = facts)

    return a

### Run eda_table function on data1 for cbistier

In [ ]:
eda_table(data1,'cbistier')

,cbistier,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,0,0.01,0.01,179.00,0.28,0.00,"11,032.33",50.99,286.54,0.45,0.04,"3,184.47",127.55
1,1,0.10,0.10,144.21,1.11,0.00,"39,083.38",160.06,226.02,0.33,0.03,"2,821.43",73.66
2,2,0.12,0.12,140.92,0.28,0.00,"13,762.89",39.36,222.45,0.30,0.03,"2,487.89",67.24
3,3,0.12,0.12,154.11,0.55,0.00,"16,933.24",84.05,243.70,0.43,0.03,"3,663.73",104.70
4,4,0.11,0.11,168.87,0.48,0.01,"13,264.04",81.42,264.13,0.52,0.03,"3,972.33",137.96
5,5,0.11,0.11,169.29,0.41,0.01,"12,125.62",70.01,273.29,0.42,0.04,"3,251.71",114.73
6,6,0.10,0.10,177.45,0.71,0.01,"22,458.52",125.19,293.38,0.50,0.04,"3,952.96",147.56
7,7,0.10,0.10,188.78,0.27,0.01,"7,778.69",51.80,314.05,0.49,0.04,"3,693.59",154.06
8,8,0.09,0.09,199.43,0.45,0.01,"11,350.42",90.13,336.54,0.52,0.04,"3,909.51",174.62
9,9,0.07,0.07,219.17,1.19,0.01,"23,075.94",260.69,370.77,0.84,0.06,"5,350.50",312.52
10,10,0.05,0.05,228.59,0.47,0.01,"14,795.56",106.72,423.79,0.47,0.06,"3,581.19",198.04
11,90,0.00,0.00,215.27,0.00,0.00,NaN,0.00,388.41,0.77,0.05,"5,841.59",299.08
12,99,0.00,0.00,194.30,0.00,0.00,NaN,0.00,290.14,0.35,0.04,"2,331.87",102.29

### Create a loop to run data1 through eda_table function for all j in list comprehension

#### Hint: Use print('------') at end of loop segment each iteration in the display

In [ ]:
for j in [i for i in data1.columns if i not in facts]:
    display(eda_table(data1,j))
    print('-------------------------------------------------------------------------------------------------------------------------------------------------')

,insstate,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,OH,1.00,1.00,173.82,0.57,0.01,"16,912.08",99.68,284.81,0.48,0.04,"3,732.69",138.08

-------------------------------------------------------------------------------------------------------------------------------------------------

,cbistier,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,0,0.01,0.01,179.00,0.28,0.00,"11,032.33",50.99,286.54,0.45,0.04,"3,184.47",127.55
1,1,0.10,0.10,144.21,1.11,0.00,"39,083.38",160.06,226.02,0.33,0.03,"2,821.43",73.66
2,2,0.12,0.12,140.92,0.28,0.00,"13,762.89",39.36,222.45,0.30,0.03,"2,487.89",67.24
3,3,0.12,0.12,154.11,0.55,0.00,"16,933.24",84.05,243.70,0.43,0.03,"3,663.73",104.70
4,4,0.11,0.11,168.87,0.48,0.01,"13,264.04",81.42,264.13,0.52,0.03,"3,972.33",137.96
5,5,0.11,0.11,169.29,0.41,0.01,"12,125.62",70.01,273.29,0.42,0.04,"3,251.71",114.73
6,6,0.10,0.10,177.45,0.71,0.01,"22,458.52",125.19,293.38,0.50,0.04,"3,952.96",147.56
7,7,0.10,0.10,188.78,0.27,0.01,"7,778.69",51.80,314.05,0.49,0.04,"3,693.59",154.06
8,8,0.09,0.09,199.43,0.45,0.01,"11,350.42",90.13,336.54,0.52,0.04,"3,909.51",174.62
9,9,0.07,0.07,219.17,1.19,0.01,"23,075.94",260.69,370.77,0.84,0.06,"5,350.50",312.52
10,10,0.05,0.05,228.59,0.47,0.01,"14,795.56",106.72,423.79,0.47,0.06,"3,581.19",198.04
11,90,0.00,0.00,215.27,0.00,0.00,NaN,0.00,388.41,0.77,0.05,"5,841.59",299.08
12,99,0.00,0.00,194.30,0.00,0.00,NaN,0.00,290.14,0.35,0.04,"2,331.87",102.29

-------------------------------------------------------------------------------------------------------------------------------------------------

,vehuse,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,B,0.00,0.00,228.34,0.41,0.01,"7,973.67",93.12,278.71,0.77,0.04,"5,018.26",214.90
1,C,0.42,0.42,186.90,0.60,0.01,"18,058.02",112.77,303.03,0.51,0.04,"4,009.36",155.48
2,F,0.01,0.01,125.78,0.00,0.00,NaN,0.00,195.25,0.29,0.01,"5,082.01",55.87
3,P,0.53,0.53,167.04,0.56,0.01,"16,963.67",92.81,274.13,0.45,0.04,"3,436.54",123.36
4,W,0.03,0.03,126.27,0.66,0.01,"9,132.68",82.82,254.17,0.70,0.04,"4,361.10",177.96
5,NaN,0.00,0.00,136.08,0.31,0.01,"3,525.00",42.38,291.69,0.29,0.03,"2,846.00",85.55

-------------------------------------------------------------------------------------------------------------------------------------------------

,numveh,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,1,0.21,0.21,210.25,0.43,0.01,"10,863.91",89.69,343.30,0.55,0.05,"3,914.62",188.97
1,2,0.39,0.39,154.86,0.62,0.01,"18,664.39",96.51,262.15,0.48,0.04,"3,453.64",125.95
2,3,0.23,0.23,165.70,0.48,0.01,"13,992.41",79.62,268.84,0.44,0.03,"3,731.40",117.48
3,4,0.11,0.11,187.66,0.43,0.01,"14,800.64",81.11,292.76,0.47,0.04,"3,854.98",137.93
4,5,0.04,0.04,184.69,1.95,0.01,"71,515.25",360.46,285.70,0.41,0.03,"4,502.96",117.61
5,6,0.01,0.01,156.31,0.92,0.00,"100,000.00",144.18,253.01,0.49,0.02,"6,613.43",123.96
6,7,0.00,0.00,179.04,0.00,0.00,NaN,0.00,281.68,0.10,0.01,"2,044.68",28.88
7,8,0.00,0.00,114.76,0.00,0.00,NaN,0.00,165.52,2.16,0.04,"9,470.99",356.87
8,9,0.00,0.00,138.04,0.00,0.00,NaN,0.00,189.48,0.00,0.00,NaN,0.00
9,10,0.00,0.00,82.68,0.00,0.00,NaN,0.00,145.19,0.00,0.00,NaN,0.00
10,11,0.00,0.00,60.50,0.00,0.00,NaN,0.00,109.03,0.00,0.00,NaN,0.00
11,12,0.00,0.00,148.00,0.00,0.00,NaN,0.00,147.33,0.00,0.00,NaN,0.00

-------------------------------------------------------------------------------------------------------------------------------------------------

,numdrv,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,1.00,0.22,0.22,179.51,0.72,0.01,"19,141.10",129.09,302.01,0.60,0.04,"4,221.33",180.53
1,2.00,0.53,0.53,143.39,0.35,0.00,"10,658.36",50.36,244.94,0.47,0.03,"3,397.61",115.00
2,3.00,0.15,0.15,210.01,0.88,0.01,"26,052.91",185.31,328.86,0.44,0.04,"3,812.81",143.16
3,4.00,0.08,0.08,260.32,0.69,0.01,"20,205.85",179.95,388.57,0.42,0.04,"4,042.77",162.48
4,5.00,0.02,0.02,325.27,0.42,0.01,"19,940.88",135.50,428.47,0.30,0.04,"3,192.44",126.55
5,6.00,0.00,0.00,264.64,0.16,0.01,"5,000.00",42.30,394.72,0.30,0.04,"2,787.59",117.90
6,7.00,0.00,0.00,325.08,0.00,0.00,NaN,0.00,359.93,0.00,0.00,NaN,0.00
7,9.00,0.00,0.00,66.10,0.00,0.00,NaN,0.00,150.57,0.00,0.00,NaN,0.00
8,10.00,0.00,0.00,83.78,0.00,0.00,NaN,0.00,150.53,0.00,0.00,NaN,0.00
9,11.00,0.00,0.00,78.37,0.00,0.00,NaN,0.00,155.45,0.00,0.00,NaN,0.00
10,13.00,0.00,0.00,132.01,0.00,0.00,NaN,0.00,600.42,0.00,0.00,NaN,0.00
11,NaN,0.00,0.00,127.77,0.00,0.00,NaN,0.00,274.95,2.28,0.06,"9,840.45",625.79

-------------------------------------------------------------------------------------------------------------------------------------------------

,modlyr,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,"1,949.00",0.00,0.00,28.27,0.00,0.00,NaN,0.00,18.18,0.00,0.00,NaN,0.00
1,"1,952.00",0.00,0.00,95.86,0.00,0.00,NaN,0.00,63.57,0.00,0.00,NaN,0.00
2,"1,964.00",0.00,0.00,39.89,0.00,0.00,NaN,0.00,49.86,0.00,0.00,NaN,0.00
3,"1,965.00",0.00,0.00,68.25,0.00,0.00,NaN,0.00,33.21,0.00,0.00,NaN,0.00
4,"1,967.00",0.00,0.00,29.14,0.00,0.00,NaN,0.00,76.44,0.00,0.00,NaN,0.00
5,"1,968.00",0.00,0.00,37.01,0.00,0.00,NaN,0.00,13.00,0.00,0.00,NaN,0.00
6,"1,969.00",0.00,0.00,40.43,0.00,0.00,NaN,0.00,82.82,0.00,0.00,NaN,0.00
7,"1,971.00",0.00,0.00,82.69,0.00,0.00,NaN,0.00,55.13,0.00,0.00,NaN,0.00
8,"1,973.00",0.00,0.00,55.14,0.00,0.00,NaN,0.00,46.37,0.00,0.00,NaN,0.00
9,"1,974.00",0.00,0.00,130.91,0.00,0.00,NaN,0.00,87.89,0.00,0.00,NaN,0.00
10,"1,976.00",0.00,0.00,69.43,0.00,0.00,NaN,0.00,51.58,0.00,0.00,NaN,0.00
11,"1,977.00",0.00,0.00,99.18,0.00,0.00,NaN,0.00,23.80,0.00,0.00,NaN,0.00
12,"1,978.00",0.00,0.00,100.01,0.00,0.00,NaN,0.00,38.00,0.00,0.00,NaN,0.00
13,"1,979.00",0.00,0.00,247.18,0.00,0.00,NaN,0.00,182.87,0.00,0.00,NaN,0.00
14,"1,981.00",0.00,0.00,59.80,0.00,0.00,NaN,0.00,20.80,0.00,0.00,NaN,0.00
15,"1,982.00",0.00,0.00,71.70,0.00,0.00,NaN,0.00,143.39,0.00,0.00,NaN,0.00
16,"1,983.00",0.00,0.00,62.16,0.00,0.00,NaN,0.00,49.21,0.00,0.00,NaN,0.00
17,"1,984.00",0.00,0.00,86.95,0.00,0.00,NaN,0.00,63.47,0.00,0.00,NaN,0.00
18,"1,985.00",0.00,0.00,34.77,0.00,0.00,NaN,0.00,78.18,0.00,0.00,NaN,0.00
19,"1,986.00",0.00,0.00,119.39,0.00,0.00,NaN,0.00,96.45,0.00,0.00,NaN,0.00
20,"1,987.00",0.00,0.00,77.50,0.00,0.00,NaN,0.00,41.52,0.00,0.00,NaN,0.00
21,"1,988.00",0.00,0.00,135.63,0.00,0.00,NaN,0.00,92.41,0.00,0.00,NaN,0.00
22,"1,989.00",0.00,0.00,74.64,0.00,0.00,NaN,0.00,48.65,0.00,0.00,NaN,0.00
23,"1,990.00",0.00,0.00,81.42,0.00,0.00,NaN,0.00,92.76,0.00,0.00,NaN,0.00
24,"1,991.00",0.00,0.00,97.43,0.00,0.00,NaN,0.00,100.42,0.00,0.00,NaN,0.00
25,"1,992.00",0.00,0.00,102.82,0.00,0.00,NaN,0.00,96.01,0.00,0.00,NaN,0.00
26,"1,993.00",0.00,0.00,97.15,0.00,0.00,NaN,0.00,145.72,0.00,0.00,NaN,0.00
27,"1,994.00",0.00,0.00,86.16,0.00,0.00,NaN,0.00,111.05,0.00,0.00,NaN,0.00
28,"1,995.00",0.00,0.00,105.38,0.00,0.00,NaN,0.00,112.45,0.00,0.00,NaN,0.00
29,"1,996.00",0.00,0.00,108.97,0.00,0.00,NaN,0.00,117.88,0.00,0.00,NaN,0.00
30,"1,997.00",0.00,0.00,96.31,1.20,0.01,"9,000.00",115.17,103.25,0.00,0.00,NaN,0.00
31,"1,998.00",0.00,0.00,109.85,0.00,0.00,NaN,0.00,132.39,0.16,0.01,"2,256.98",20.68
32,"1,999.00",0.00,0.00,108.39,0.00,0.00,NaN,0.00,124.99,0.05,0.01,525.87,6.54
33,"2,000.00",0.00,0.00,108.07,0.00,0.00,NaN,0.00,130.88,0.53,0.02,"2,918.46",69.64
34,"2,001.00",0.01,0.01,114.95,0.43,0.01,"7,129.30",49.11,146.56,0.49,0.03,"2,322.67",71.99
35,"2,002.00",0.01,0.01,125.36,1.57,0.01,"38,347.03",196.51,165.43,0.65,0.04,"2,994.31",107.41
36,"2,003.00",0.01,0.01,124.59,0.00,0.00,NaN,0.00,155.33,0.45,0.03,"2,529.38",69.20
37,"2,004.00",0.01,0.01,129.96,0.39,0.01,"5,525.34",51.21,172.95,0.64,0.03,"3,524.23",111.05
38,"2,005.00",0.01,0.01,123.78,0.60,0.01,"8,323.22",74.04,170.24,0.50,0.03,"2,865.31",84.97
39,"2,006.00",0.01,0.01,132.05,0.33,0.01,"5,946.64",43.74,198.38,0.72,0.03,"4,212.91",142.53
40,"2,007.00",0.01,0.01,131.96,1.40,0.01,"15,154.60",184.89,200.96,0.56,0.04,"3,086.33",112.96
41,"2,008.00",0.01,0.01,133.31,0.89,0.01,"10,368.67",118.32,215.32,0.81,0.04,"4,557.35",173.36
42,"2,009.00",0.01,0.01,124.86,0.05,0.00,"3,000.00",6.03,225.72,0.40,0.02,"3,718.27",89.68
43,"2,010.00",0.01,0.01,123.64,0.24,0.01,"3,935.28",30.08,232.59,0.65,0.03,"4,739.11",152.15
44,"2,011.00",0.01,0.01,120.47,0.65,0.00,"19,483.33",78.61,229.37,0.33,0.03,"2,697.65",76.19
45,"2,012.00",0.01,0.01,123.27,0.31,0.01,"7,017.43",38.58,266.26,0.64,0.04,"3,894.59",171.28
46,"2,013.00",0.01,0.01,118.27,0.82,0.01,"19,105.25",96.91,266.66,0.54,0.04,"3,326.61",143.43
47,"2,014.00",0.01,0.01,115.91,0.21,0.00,"6,720.33",24.14,276.28,0.49,0.03,"4,352.09",135.50
48,"2,015.00",0.01,0.01,111.60,0.33,0.01,"7,245.82",37.32,271.31,0.55,0.05,"3,336.40",150.35
49,"2,016.00",0.01,0.01,111.70,0.01,0.00,750.00,1.33,273.41,0.63,0.04,"4,022.92",171.42
50,"2,017.00",0.01,0.01,116.58,0.72,0.01,"14,363.33",83.67,301.36,0.52,0.03,"4,462.96",155.99
51,"2,018.00",0.00,0.00,102.56,0.00,0.00,NaN,0.00,256.83,0.65,0.03,"5,152.29",166.31
52,"2,019.00",0.00,0.00,66.61,0.00,0.00,NaN,0.00,160.92,0.00,0.00,NaN,0.00
53,NaN,0.79,0.79,187.59,0.59,0.01,"18,466.38",109.89,301.97,0.47,0.04,"3,755.07",142.61

-------------------------------------------------------------------------------------------------------------------------------------------------

,make,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,NaN,1.00,1.00,173.82,0.57,0.01,"16,912.08",99.68,284.81,0.48,0.04,"3,732.69",138.08

-------------------------------------------------------------------------------------------------------------------------------------------------

,model,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,NaN,1.00,1.00,173.82,0.57,0.01,"16,912.08",99.68,284.81,0.48,0.04,"3,732.69",138.08

-------------------------------------------------------------------------------------------------------------------------------------------------

,collsymb,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,0.00,0.00,0.00,82.95,0.00,0.00,NaN,0.00,97.40,0.00,0.00,NaN,0.00
1,1.00,0.00,0.00,201.07,0.23,0.01,"6,400.00",46.94,134.47,0.55,0.02,"3,364.85",74.04
2,2.00,0.00,0.00,193.07,0.01,0.01,128.05,1.18,156.05,0.96,0.04,"4,076.51",149.99
3,3.00,0.00,0.00,160.48,0.00,0.00,NaN,0.00,138.01,0.10,0.05,311.80,14.11
4,4.00,0.00,0.00,154.41,0.00,0.00,NaN,0.00,114.60,0.14,0.01,"1,282.96",16.40
5,5.00,0.00,0.00,186.08,0.00,0.00,NaN,0.00,142.16,1.16,0.03,"6,339.03",165.45
6,6.00,0.01,0.01,158.06,0.58,0.00,"20,275.00",91.09,161.20,0.37,0.02,"2,948.04",59.60
7,7.00,0.01,0.01,166.68,0.17,0.00,"10,639.00",29.09,167.18,0.27,0.01,"3,671.95",45.17
8,8.00,0.03,0.03,171.53,0.41,0.00,"14,905.21",71.16,171.42,0.37,0.03,"2,512.37",63.40
9,10.00,0.04,0.04,172.69,0.37,0.01,"9,032.55",63.68,190.61,0.44,0.03,"2,730.43",83.42
10,11.00,0.05,0.05,175.39,0.61,0.01,"15,024.10",107.56,196.37,0.50,0.03,"3,033.64",98.72
11,12.00,0.07,0.07,173.23,0.60,0.00,"20,988.28",103.09,212.72,0.52,0.03,"3,330.97",111.08
12,13.00,0.07,0.07,175.49,0.63,0.01,"19,079.59",110.21,222.64,0.35,0.03,"2,731.87",77.53
13,14.00,0.08,0.08,176.52,0.27,0.00,"10,961.17",47.58,230.67,0.37,0.03,"3,116.44",84.73
14,15.00,0.07,0.07,178.09,0.64,0.01,"15,966.16",114.83,259.53,0.42,0.03,"3,303.32",109.78
15,16.00,0.06,0.06,182.11,0.31,0.01,"10,400.37",57.14,265.51,0.29,0.03,"2,552.51",76.76
16,17.00,0.05,0.05,174.16,0.23,0.01,"5,616.73",39.69,278.66,0.51,0.04,"3,545.36",141.96
17,18.00,0.04,0.04,174.95,1.19,0.01,"33,376.16",207.73,281.48,0.64,0.04,"4,063.45",178.98
18,19.00,0.03,0.03,174.57,0.63,0.00,"48,982.50",109.43,300.32,0.59,0.05,"3,899.00",176.39
19,20.00,0.03,0.03,171.02,0.34,0.01,"9,970.49",58.54,296.13,0.27,0.03,"2,432.54",79.34
20,21.00,0.03,0.03,165.26,0.11,0.00,"6,911.38",17.49,299.58,0.44,0.04,"3,631.44",130.93
21,22.00,0.03,0.03,162.21,0.14,0.00,"4,655.90",22.12,312.06,0.45,0.04,"3,542.46",141.86
22,23.00,0.02,0.02,173.63,0.77,0.01,"19,177.60",132.97,325.90,1.08,0.05,"6,920.99",351.92
23,24.00,0.02,0.02,158.56,0.56,0.01,"10,394.97",88.84,329.56,0.51,0.04,"4,427.82",167.15
24,25.00,0.02,0.02,169.07,0.39,0.00,"14,402.60",65.35,346.31,0.44,0.05,"3,098.16",151.82
25,26.00,0.02,0.02,171.70,0.76,0.01,"11,050.30",130.36,352.20,0.83,0.04,"7,040.84",293.49
26,27.00,0.02,0.02,172.55,0.37,0.00,"17,719.36",63.75,352.99,0.40,0.04,"3,545.86",140.33
27,28.00,0.02,0.02,174.74,1.29,0.01,"42,313.99",225.20,353.21,0.53,0.04,"4,305.72",187.91
28,29.00,0.02,0.02,173.31,0.49,0.01,"9,521.33",85.62,369.55,0.55,0.05,"4,143.23",202.84
29,30.00,0.02,0.02,183.17,1.06,0.01,"17,986.22",194.64,389.39,0.58,0.06,"3,690.78",227.66
30,31.00,0.02,0.02,171.90,0.34,0.01,"5,914.51",58.91,383.14,0.47,0.05,"3,699.38",180.13
31,32.00,0.02,0.02,174.93,0.27,0.01,"8,312.16",46.59,392.06,0.52,0.07,"3,137.28",205.15
32,33.00,0.01,0.01,182.46,0.07,0.00,"3,455.70",12.43,395.20,0.29,0.04,"3,099.89",115.25
33,34.00,0.01,0.01,181.43,7.28,0.01,"117,109.28","1,320.43",396.65,0.65,0.05,"4,974.65",259.42
34,35.00,0.01,0.01,177.97,0.14,0.00,"6,263.21",24.30,391.87,0.54,0.04,"5,212.63",212.38
35,36.00,0.01,0.01,164.26,0.74,0.00,"28,650.00",120.88,390.64,0.54,0.05,"4,149.74",210.10
36,37.00,0.01,0.01,163.36,0.63,0.01,"16,463.64",102.21,388.81,0.52,0.04,"4,647.86",201.98
37,38.00,0.01,0.01,181.40,0.16,0.00,"9,800.00",29.42,425.61,0.35,0.03,"4,910.53",147.43
38,39.00,0.01,0.01,201.42,0.24,0.01,"4,710.67",48.34,438.09,0.43,0.04,"4,561.57",187.26
39,40.00,0.00,0.00,167.96,0.54,0.01,"12,300.49",90.72,416.72,0.81,0.07,"5,092.75",338.03
40,41.00,0.01,0.01,176.39,0.00,0.00,NaN,0.00,430.20,0.13,0.02,"3,510.93",57.80
41,42.00,0.00,0.00,198.34,0.19,0.01,"3,776.89",36.70,458.33,0.48,0.03,"7,517.22",219.16
42,43.00,0.00,0.00,165.72,3.49,0.01,"39,858.97",578.23,475.22,0.57,0.04,"7,500.61",272.03
43,44.00,0.00,0.00,174.84,0.00,0.00,NaN,0.00,427.70,0.41,0.05,"3,817.53",173.71
44,45.00,0.00,0.00,180.10,0.00,0.00,NaN,0.00,465.52,0.38,0.05,"3,422.82",174.99
45,46.00,0.00,0.00,160.55,0.24,0.01,"4,350.00",38.09,438.83,0.64,0.05,"5,330.17",280.07
46,47.00,0.00,0.00,149.70,0.00,0.00,NaN,0.00,409.28,0.07,0.02,"1,511.93",30.37
47,48.00,0.00,0.00,160.66,0.00,0.00,NaN,0.00,458.19,0.69,0.08,"3,995.75",315.16
48,49.00,0.00,0.00,163.36,0.40,0.02,"4,188.65",65.28,448.68,0.80,0.09,"4,184.96",358.70
49,50.00,0.00,0.00,152.73,0.00,0.00,NaN,0.00,435.53,0.14,0.04,"1,661.37",61.23
50,51.00,0.00,0.00,152.98,0.07,0.01,"1,200.00",10.78,454.52,1.39,0.05,"11,695.10",630.23
51,52.00,0.00,0.00,163.11,0.06,0.01,835.07,9.20,441.60,0.69,0.09,"3,449.83",303.91
52,53.00,0.00,0.00,167.58,0.00,0.00,NaN,0.00,464.67,0.09,0.03,"1,349.33",43.41
53,54.00,0.00,0.00,157.03,0.00,0.00,NaN,0.00,482.85,0.45,0.03,"6,394.14",218.59
54,55.00,0.00,0.00,144.22,0.00,0.00,NaN,0.00,448.23,1.05,0.04,"10,841.01",471.84
55,56.00,0.00,0.00,160.17,0.05,0.01,850.00,8.36,512.47,1.28,0.08,"8,314.92",654.60
56,57.00,0.00,0.00,150.19,0.00,0.00,NaN,0.00,491.52,0.61,0.06,"5,298.01",301.72
57,58.00,0.00,0.00,164.22,1.03,0.01,"12,301.00",168.81,536.65,0.45,0.05,"4,376.64",240.24
58,59.00,0.00,0.00,208.69,0.00,0.00,NaN,0.00,750.01,0.31,0.09,"2,667.69",233.14
59,60.00,0.00,0.00,169.03,0.00,0.00,NaN,0.00,617.84,0.18,0.06,"1,903.65",111.76
60,61.00,0.00,0.00,158.68,0.00,0.00,NaN,0.00,499.32,0.01,0.03,215.00,5.99
61,62.00,0.00,0.00,132.86,0.00,0.00,NaN,0.00,412.15,0.00,0.00,NaN,0.00
62,63.00,0.00,0.00,147.18,0.00,0.00,NaN,0.00,523.33,1.39,0.10,"7,038.41",727.09
63,64.00,0.00,0.00,192.51,0.00,0.00,NaN,0.00,735.68,0.39,0.03,"9,416.37",285.32
64,65.00,0.00,0.00,143.12,0.00,0.00,NaN,0.00,612.99,0.00,0.00,NaN,0.00
65,66.00,0.00,0.00,283.38,0.00,0.00,NaN,0.00,790.95,0.00,0.00,NaN,0.00
66,67.00,0.00,0.00,155.94,0.00,0.00,NaN,0.00,697.68,0.00,0.00,NaN,0.00
67,68.00,0.00,0.00,105.36,0.00,0.00,NaN,0.00,673.80,0.00,0.00,NaN,0.00
68,69.00,0.00,0.00,109.17,0.00,0.00,NaN,0.00,446.18,0.00,0.00,NaN,0.00
69,70.00,0.00,0.00,99.97,0.00,0.00,NaN,0.00,744.27,0.00,0.00,NaN,0.00
70,71.00,0.00,0.00,140.19,0.00,0.00,NaN,0.00,966.47,0.00,0.00,NaN,0.00
71,73.00,0.00,0.00,112.37,0.00,0.00,NaN,0.00,"2,238.00",0.00,0.00,NaN,0.00
72,75.00,0.00,0.00,403.03,0.00,0.00,NaN,0.00,"8,436.52",0.00,0.00,NaN,0.00
73,NaN,0.00,0.00,319.73,2.63,0.15,"5,700.56",841.62,523.77,0.00,0.00,NaN,0.00

-------------------------------------------------------------------------------------------------------------------------------------------------

,perslimbi,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,"25,000.00",0.04,0.04,189.08,0.51,0.01,"9,374.32",97.25,422.87,0.41,0.05,"3,296.70",172.32
1,"30,000.00",0.00,0.00,135.07,0.00,0.00,NaN,0.00,352.18,0.00,0.00,NaN,0.00
2,"50,000.00",0.10,0.10,171.17,0.65,0.01,"13,167.75",110.61,324.95,0.45,0.04,"3,429.34",146.54
3,"100,000.00",0.56,0.56,170.10,0.56,0.01,"15,708.71",95.16,281.00,0.50,0.04,"3,658.66",140.06
4,"250,000.00",0.18,0.18,184.71,0.72,0.00,"30,648.48",133.47,266.63,0.53,0.03,"4,493.46",140.03
5,"300,000.00",0.05,0.05,156.96,0.17,0.00,"9,235.52",27.10,245.30,0.46,0.03,"3,642.64",113.59
6,"500,000.00",0.07,0.07,181.91,0.45,0.00,"20,052.86",82.44,248.15,0.41,0.03,"3,553.85",101.36
7,"1,000,000.00",0.00,0.00,82.69,0.00,0.00,NaN,0.00,124.73,0.00,0.00,NaN,0.00
8,NaN,0.00,0.00,4.57,116.28,0.07,"8,000.00",531.39,9.70,0.00,0.00,NaN,0.00

-------------------------------------------------------------------------------------------------------------------------------------------------

,acclimbi,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,"50,000.00",0.04,0.04,189.35,0.51,0.01,"9,374.32",97.20,423.07,0.41,0.05,"3,296.70",172.23
1,"60,000.00",0.00,0.00,135.07,0.00,0.00,NaN,0.00,352.18,0.00,0.00,NaN,0.00
2,"100,000.00",0.10,0.10,171.13,0.65,0.01,"13,167.75",110.54,325.00,0.45,0.04,"3,429.34",146.44
3,"200,000.00",0.00,0.00,89.50,0.00,0.00,NaN,0.00,152.25,0.00,0.00,NaN,0.00
4,"300,000.00",0.59,0.59,170.13,0.53,0.01,"15,575.82",90.83,279.67,0.49,0.04,"3,654.72",138.37
5,"500,000.00",0.27,0.27,180.23,0.64,0.00,"26,119.73",115.78,259.02,0.50,0.03,"4,211.09",129.57
6,"1,000,000.00",0.00,0.00,182.77,0.00,0.00,NaN,0.00,296.41,0.00,0.00,NaN,0.00
7,NaN,0.00,0.00,63.83,0.00,0.00,NaN,0.00,79.78,0.00,0.00,NaN,0.00

-------------------------------------------------------------------------------------------------------------------------------------------------

,deductiblecol,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,50.00,0.00,0.00,179.12,0.00,0.00,NaN,0.00,433.81,0.80,0.20,"1,746.67",349.18
1,100.00,0.02,0.02,154.30,0.41,0.00,"16,415.66",63.71,312.03,0.42,0.05,"2,565.77",131.93
2,200.00,0.02,0.02,153.96,0.07,0.00,"5,750.00",10.63,279.86,0.28,0.03,"2,401.09",77.65
3,250.00,0.21,0.21,154.95,0.41,0.01,"12,166.16",63.05,274.15,0.44,0.04,"3,112.44",121.49
4,350.00,0.00,0.00,128.63,0.00,0.00,NaN,0.00,198.39,4.36,0.10,"8,421.83",865.16
5,500.00,0.65,0.65,179.87,0.62,0.01,"17,806.64",110.99,295.50,0.49,0.04,"3,859.20",144.54
6,750.00,0.00,0.00,155.71,0.00,0.00,NaN,0.00,226.42,0.12,0.06,446.81,27.70
7,"1,000.00",0.08,0.08,198.18,0.65,0.01,"22,007.30",128.84,258.11,0.47,0.02,"4,899.33",121.90
8,"1,500.00",0.00,0.00,272.57,0.05,0.01,"1,732.84",13.76,359.02,1.06,0.02,"15,988.06",380.86
9,"2,000.00",0.00,0.00,192.10,0.00,0.00,NaN,0.00,188.28,0.00,0.00,NaN,0.00
10,"2,500.00",0.00,0.00,320.31,0.00,0.00,NaN,0.00,242.87,0.00,0.00,NaN,0.00
11,"5,000.00",0.00,0.00,42.63,0.00,0.00,NaN,0.00,138.22,0.00,0.00,NaN,0.00
12,NaN,0.01,0.01,39.69,3.99,0.01,"14,942.88",158.20,37.55,6.73,0.05,"5,220.74",252.67

-------------------------------------------------------------------------------------------------------------------------------------------------

,pol_eff_date,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,2014-01-01,0.00,0.00,129.18,0.00,0.00,NaN,0.00,228.25,1.17,0.07,"3,921.53",266.65
1,2014-01-02,0.00,0.00,93.35,0.00,0.00,NaN,0.00,263.23,0.00,0.00,NaN,0.00
2,2014-01-03,0.00,0.00,98.24,0.00,0.00,NaN,0.00,187.38,0.00,0.00,NaN,0.00
3,2014-01-04,0.00,0.00,143.09,0.00,0.00,NaN,0.00,255.05,0.00,0.00,NaN,0.00
4,2014-01-05,0.00,0.00,69.93,0.00,0.00,NaN,0.00,140.77,0.00,0.00,NaN,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2174,2019-12-27,0.00,0.00,168.13,0.00,0.00,NaN,0.00,282.74,0.61,0.11,"1,571.15",171.74
2175,2019-12-28,0.00,0.00,188.31,0.15,0.03,"1,018.05",28.54,327.02,0.65,0.06,"3,764.15",211.08
2176,2019-12-29,0.00,0.00,128.29,0.00,0.00,NaN,0.00,223.37,0.36,0.08,"1,044.21",80.32
2177,2019-12-30,0.00,0.00,191.78,0.00,0.00,NaN,0.00,270.89,0.82,0.09,"2,351.28",221.73
2178,2019-12-31,0.00,0.00,140.64,0.00,0.00,NaN,0.00,242.40,0.00,0.00,NaN,0.00

-------------------------------------------------------------------------------------------------------------------------------------------------

,pol_exp_date,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,01/01/2015,0.00,0.00,129.79,0.00,0.00,NaN,0.00,226.94,1.31,0.08,"3,921.53",296.47
1,01/01/2016,0.00,0.00,176.34,0.00,0.00,NaN,0.00,275.49,2.04,0.09,"6,597.29",563.17
2,01/01/2017,0.00,0.00,171.53,0.00,0.00,NaN,0.00,291.76,0.47,0.03,"4,008.19",137.44
3,01/01/2018,0.00,0.00,215.14,0.02,0.02,288.00,5.31,346.87,0.89,0.06,"5,554.62",307.53
4,01/01/2019,0.00,0.00,217.89,0.00,0.00,NaN,0.00,330.79,0.15,0.04,"1,303.46",50.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2343,12/31/2016,0.00,0.00,98.86,0.00,0.00,NaN,0.00,259.34,0.00,0.00,NaN,0.00
2344,12/31/2017,0.00,0.00,173.91,0.00,0.00,NaN,0.00,321.54,0.00,0.00,NaN,0.00
2345,12/31/2018,0.00,0.00,456.15,0.00,0.00,NaN,0.00,921.07,0.00,0.00,NaN,0.00
2346,12/31/2019,0.00,0.00,229.39,0.00,0.00,NaN,0.00,447.05,0.00,0.00,NaN,0.00
2347,12/31/2020,0.00,0.00,140.64,0.00,0.00,NaN,0.00,242.40,0.00,0.00,NaN,0.00

-------------------------------------------------------------------------------------------------------------------------------------------------

,pol_eff_year,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,2014,0.04,0.04,106.08,0.54,0.01,"8,375.68",57.28,202.03,0.58,0.04,"3,141.93",118.18
1,2015,0.20,0.20,159.65,0.77,0.01,"20,053.10",123.18,262.07,0.48,0.04,"3,284.56",125.66
2,2016,0.20,0.20,165.96,0.59,0.01,"17,395.65",98.09,284.80,0.47,0.04,"3,553.75",133.69
3,2017,0.20,0.20,175.37,0.77,0.01,"19,199.19",134.54,293.35,0.53,0.04,"4,181.90",155.06
4,2018,0.19,0.19,185.52,0.39,0.00,"15,361.34",72.70,295.41,0.43,0.04,"3,461.27",125.58
5,2019,0.17,0.17,202.21,0.36,0.01,"12,839.80",72.69,310.73,0.51,0.04,"4,466.45",157.44

-------------------------------------------------------------------------------------------------------------------------------------------------

,DrvAge,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,0.00,0.00,0.00,148.55,0.00,0.00,NaN,0.00,176.66,0.00,0.00,NaN,0.00
1,13.00,0.00,0.00,54.87,0.00,0.00,NaN,0.00,138.03,0.00,0.00,NaN,0.00
2,14.00,0.00,0.00,118.44,0.00,0.00,NaN,0.00,213.99,0.00,0.00,NaN,0.00
3,15.00,0.00,0.00,286.77,0.00,0.00,NaN,0.00,465.65,0.49,0.05,"4,583.51",228.45
4,16.00,0.00,0.00,297.56,0.00,0.00,NaN,0.00,419.30,0.11,0.02,"2,606.85",47.51
5,17.00,0.01,0.01,334.42,0.16,0.01,"5,163.82",53.98,418.13,0.47,0.04,"5,005.06",196.19
6,18.00,0.01,0.01,328.38,1.48,0.01,"41,250.00",486.69,440.09,0.52,0.04,"5,143.66",230.62
7,19.00,0.01,0.01,323.50,1.41,0.02,"21,528.11",457.27,447.16,0.43,0.05,"3,980.02",194.44
8,20.00,0.01,0.01,299.45,0.43,0.01,"12,837.80",127.91,422.19,0.49,0.06,"3,576.53",206.68
9,21.00,0.01,0.01,264.65,0.17,0.01,"5,809.83",44.88,404.01,0.33,0.03,"4,374.30",135.16
10,22.00,0.01,0.01,257.64,1.08,0.01,"22,078.29",279.16,413.80,0.69,0.07,"4,279.88",286.04
11,23.00,0.01,0.01,245.41,0.01,0.00,800.63,2.70,399.26,0.38,0.04,"4,040.61",149.99
12,24.00,0.01,0.01,220.26,2.05,0.01,"42,871.33",451.60,363.97,0.35,0.04,"3,499.13",129.01
13,25.00,0.01,0.01,210.22,0.18,0.00,"7,928.53",38.60,353.48,0.45,0.03,"5,419.89",158.30
14,26.00,0.01,0.01,188.84,0.38,0.01,"11,816.06",71.50,343.33,0.47,0.03,"6,290.26",161.76
15,27.00,0.01,0.01,185.85,0.70,0.01,"13,062.64",130.40,333.68,0.54,0.05,"3,933.01",179.48
16,28.00,0.01,0.01,181.13,0.65,0.01,"16,332.19",117.53,322.08,0.57,0.04,"4,258.23",183.86
17,29.00,0.01,0.01,167.25,1.56,0.01,"37,394.90",260.44,305.41,0.44,0.03,"4,586.54",134.16
18,30.00,0.01,0.01,159.27,0.62,0.01,"10,039.77",99.01,302.85,0.44,0.04,"3,467.78",131.90
19,31.00,0.01,0.01,158.39,0.52,0.01,"10,233.27",82.88,289.45,0.82,0.04,"5,303.42",236.23
20,32.00,0.01,0.01,151.59,0.33,0.01,"9,297.66",50.51,272.34,0.41,0.04,"3,138.91",110.85
21,33.00,0.01,0.01,153.40,0.72,0.01,"16,122.30",110.30,272.94,0.63,0.04,"4,689.27",173.24
22,34.00,0.01,0.01,149.63,1.27,0.01,"17,825.27",190.76,266.95,0.61,0.03,"4,907.27",164.11
23,35.00,0.01,0.01,152.57,0.30,0.01,"8,986.42",46.05,263.91,0.64,0.04,"3,897.65",169.78
24,36.00,0.01,0.01,159.51,0.93,0.01,"24,489.24",147.72,276.05,0.54,0.04,"3,734.35",148.67
25,37.00,0.01,0.01,158.94,2.32,0.01,"51,609.21",368.80,288.00,0.56,0.04,"3,980.26",161.18
26,38.00,0.01,0.01,166.40,0.08,0.00,"5,650.00",13.69,290.73,0.33,0.03,"3,195.77",96.81
27,39.00,0.01,0.01,179.09,0.18,0.01,"6,416.25",32.36,305.19,1.27,0.04,"8,796.70",388.18
28,40.00,0.01,0.01,179.75,0.26,0.01,"6,152.21",46.13,312.09,0.43,0.04,"3,446.29",133.52
29,41.00,0.01,0.01,174.27,0.32,0.01,"9,278.67",56.56,298.90,0.38,0.03,"3,440.15",113.24
30,42.00,0.01,0.01,186.21,1.06,0.01,"32,579.00",197.21,306.99,0.65,0.05,"4,339.45",199.63
31,43.00,0.02,0.02,190.08,1.89,0.01,"27,814.79",360.11,310.46,0.49,0.04,"3,434.72",153.62
32,44.00,0.02,0.02,193.16,0.32,0.01,"11,220.77",62.16,325.54,0.77,0.06,"4,365.51",251.51
33,45.00,0.02,0.02,194.32,0.36,0.01,"10,793.62",70.52,322.02,0.51,0.04,"4,098.11",165.11
34,46.00,0.02,0.02,194.32,0.24,0.01,"4,600.55",47.37,327.21,0.53,0.05,"3,654.26",173.10
35,47.00,0.02,0.02,200.98,0.48,0.01,"16,244.46",97.41,328.09,0.38,0.04,"3,407.83",126.02
36,48.00,0.02,0.02,196.46,0.70,0.00,"28,176.94",137.76,324.50,0.30,0.04,"2,760.83",97.19
37,49.00,0.02,0.02,191.77,1.86,0.02,"19,936.62",357.35,319.53,1.20,0.05,"7,674.04",382.09
38,50.00,0.02,0.02,179.52,3.36,0.01,"100,857.99",603.75,296.31,0.47,0.04,"3,498.86",139.63
39,51.00,0.02,0.02,184.39,0.29,0.00,"11,498.00",54.03,308.38,0.26,0.02,"3,332.01",81.42
40,52.00,0.02,0.02,177.23,0.06,0.00,"3,930.55",10.83,294.74,0.23,0.03,"2,199.24",66.63
41,53.00,0.02,0.02,169.20,0.11,0.00,"5,325.00",18.55,280.62,0.54,0.04,"3,383.65",150.32
42,54.00,0.02,0.02,166.95,0.43,0.01,"8,313.54",72.53,275.35,0.50,0.04,"3,715.15",138.48
43,55.00,0.02,0.02,164.39,0.84,0.01,"25,502.00",138.09,265.71,0.37,0.03,"2,921.25",99.43
44,56.00,0.02,0.02,156.39,0.84,0.01,"23,913.29",130.81,255.28,0.58,0.04,"3,746.79",149.33
45,57.00,0.02,0.02,153.13,0.36,0.01,"9,261.05",55.25,248.18,0.50,0.04,"3,279.25",124.71
46,58.00,0.02,0.02,149.63,0.07,0.00,"3,777.59",11.17,241.03,0.41,0.03,"3,211.36",99.73
47,59.00,0.02,0.02,148.27,0.16,0.00,"8,081.38",23.73,239.30,0.39,0.03,"3,166.71",92.98
48,60.00,0.02,0.02,144.44,0.76,0.00,"24,188.33",109.59,234.87,0.34,0.03,"3,065.21",81.01
49,61.00,0.02,0.02,139.60,0.37,0.00,"13,733.74",51.95,230.71,0.54,0.03,"4,432.01",124.05
50,62.00,0.02,0.02,138.90,0.07,0.00,"3,255.70",9.83,231.97,0.46,0.03,"3,536.90",106.79
51,63.00,0.02,0.02,135.53,0.14,0.01,"3,223.79",18.48,220.85,0.66,0.04,"4,049.31",145.09
52,64.00,0.02,0.02,135.80,0.13,0.00,"7,547.58",17.90,222.31,0.37,0.02,"3,388.38",83.06
53,65.00,0.02,0.02,138.99,0.22,0.00,"9,193.74",31.06,227.57,0.31,0.03,"2,269.94",70.94
54,66.00,0.02,0.02,141.82,0.00,0.00,374.00,0.66,234.66,0.35,0.03,"2,801.01",81.10
55,67.00,0.02,0.02,144.54,0.36,0.00,"14,380.13",52.21,233.99,0.46,0.04,"2,428.50",108.01
56,68.00,0.02,0.02,146.55,0.00,0.00,221.64,0.22,236.02,0.26,0.03,"1,830.13",60.62
57,69.00,0.02,0.02,152.54,0.36,0.00,"13,073.68",54.94,249.19,0.46,0.03,"3,329.16",115.43
58,70.00,0.02,0.02,148.46,0.21,0.00,"6,770.88",31.66,244.67,0.47,0.03,"3,780.69",114.89
59,71.00,0.01,0.01,152.14,0.11,0.00,"6,841.85",17.41,249.31,0.44,0.03,"3,572.52",109.07
60,72.00,0.01,0.01,160.08,0.04,0.00,"2,511.40",7.13,256.27,0.37,0.03,"3,516.74",94.84
61,73.00,0.01,0.01,158.74,0.09,0.01,"2,115.44",13.59,258.76,0.35,0.05,"1,956.05",91.10
62,74.00,0.01,0.01,166.08,0.24,0.01,"7,589.67",39.12,254.44,0.35,0.04,"2,169.27",89.46
63,75.00,0.01,0.01,171.12,0.21,0.01,"6,565.67",36.44,261.64,0.57,0.05,"3,111.98",149.69
64,76.00,0.01,0.01,169.83,1.57,0.00,"65,250.00",265.80,265.95,0.50,0.03,"3,856.51",133.53
65,77.00,0.01,0.01,172.11,0.13,0.00,"4,890.65",22.29,268.36,0.19,0.03,"1,601.57",51.08
66,78.00,0.01,0.01,173.62,0.03,0.01,"1,189.83",6.02,266.30,0.39,0.03,"3,390.85",102.91
67,79.00,0.01,0.01,175.80,0.41,0.01,"12,934.55",71.82,269.06,0.22,0.03,"1,779.17",59.28
68,80.00,0.01,0.01,185.04,0.00,0.00,NaN,0.00,276.72,0.26,0.04,"1,704.15",72.49
69,81.00,0.00,0.00,183.53,1.03,0.01,"25,425.00",189.25,274.73,0.67,0.05,"3,791.45",183.44
70,82.00,0.00,0.00,190.33,0.16,0.00,"7,350.35",30.82,275.52,0.46,0.05,"2,538.90",127.77
71,83.00,0.00,0.00,188.62,0.00,0.00,NaN,0.00,279.08,0.49,0.03,"5,425.28",137.70
72,84.00,0.00,0.00,180.77,0.00,0.00,NaN,0.00,275.80,0.38,0.05,"2,278.10",104.48
73,85.00,0.00,0.00,194.91,0.24,0.01,"3,443.50",47.72,277.73,0.28,0.02,"3,692.88",76.77
74,86.00,0.00,0.00,204.21,0.17,0.02,"1,955.86",35.56,321.79,0.76,0.08,"2,987.44",244.45
75,87.00,0.00,0.00,213.54,0.00,0.00,NaN,0.00,309.69,0.13,0.04,894.99,39.76
76,88.00,0.00,0.00,222.19,0.53,0.03,"4,297.86",116.82,306.53,1.55,0.11,"4,370.71",475.21
77,89.00,0.00,0.00,201.39,0.00,0.00,NaN,0.00,298.65,0.66,0.04,"5,326.67",198.53
78,90.00,0.00,0.00,200.27,0.61,0.02,"5,500.00",122.52,299.85,0.40,0.04,"2,665.78",118.77
79,91.00,0.00,0.00,217.80,0.00,0.00,NaN,0.00,298.09,0.00,0.00,NaN,0.00
80,92.00,0.00,0.00,228.95,1.48,0.03,"10,500.00",339.53,309.00,0.37,0.06,"1,765.23",114.16
81,93.00,0.00,0.00,208.78,0.00,0.00,NaN,0.00,303.73,0.00,0.00,NaN,0.00
82,94.00,0.00,0.00,249.68,0.00,0.00,NaN,0.00,340.61,0.00,0.00,NaN,0.00
83,95.00,0.00,0.00,226.26,0.00,0.00,NaN,0.00,340.78,0.00,0.00,NaN,0.00
84,96.00,0.00,0.00,206.18,0.00,0.00,NaN,0.00,213.06,0.00,0.00,NaN,0.00
85,97.00,0.00,0.00,173.52,0.00,0.00,NaN,0.00,210.37,0.00,0.00,NaN,0.00
86,99.00,0.00,0.00,165.78,0.00,0.00,NaN,0.00,310.19,0.00,0.00,NaN,0.00
87,NaN,0.00,0.00,85.65,2.59,0.03,"8,000.00",222.13,186.01,1.38,0.03,"9,233.00",256.37

-------------------------------------------------------------------------------------------------------------------------------------------------

,DrvSex,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,F,0.48,0.48,174.44,0.56,0.01,"17,297.10",98.19,284.35,0.45,0.04,"3,359.01",129.18
1,M,0.52,0.52,173.35,0.58,0.01,"16,625.27",100.92,285.38,0.51,0.04,"4,105.04",146.28
2,NaN,0.00,0.00,88.71,2.44,0.03,"8,000.00",216.11,184.56,1.35,0.03,"9,233.00",249.42

-------------------------------------------------------------------------------------------------------------------------------------------------

,DrvMarSts,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,M,0.62,0.62,156.45,0.48,0.00,"15,382.64",75.17,261.34,0.45,0.03,"3,468.72",117.86
1,S,0.30,0.30,206.20,0.72,0.01,"19,678.56",148.81,329.73,0.51,0.04,"4,193.58",168.96
2,W,0.04,0.04,183.58,0.40,0.01,"11,626.05",74.04,291.03,0.65,0.05,"3,668.35",190.23
3,X,0.04,0.04,191.54,0.69,0.01,"16,403.69",132.94,306.46,0.54,0.04,"3,745.89",166.16
4,NaN,0.00,0.00,85.65,2.59,0.03,"8,000.00",222.13,186.01,1.38,0.03,"9,233.00",256.37

-------------------------------------------------------------------------------------------------------------------------------------------------

,color_exterior,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,BEIGE,0.01,0.01,173.98,0.91,0.01,"31,000.00",158.53,282.77,0.34,0.03,"2,891.08",96.10
1,BLACK,0.10,0.10,181.50,0.60,0.01,"18,721.17",109.61,350.96,0.53,0.05,"4,054.29",187.02
2,BLUE,0.05,0.05,179.29,1.56,0.01,"39,085.21",279.17,325.25,0.47,0.04,"4,065.85",151.32
3,BROWN,0.01,0.01,180.45,0.10,0.01,"3,551.70",18.65,315.01,0.32,0.04,"2,545.10",100.24
4,DARK BLUE,0.00,0.00,188.21,0.00,0.00,NaN,0.00,303.90,0.36,0.04,"2,997.39",109.74
5,DARK BROWN,0.00,0.00,209.14,0.00,0.00,NaN,0.00,591.23,0.00,0.00,NaN,0.00
6,DARK GRAY,0.01,0.01,167.53,0.28,0.01,"8,491.93",46.29,336.83,0.33,0.05,"2,381.40",110.34
7,DARK GREEN,0.00,0.00,145.47,0.00,0.00,NaN,0.00,164.58,0.00,0.00,NaN,0.00
8,GOLD,0.01,0.01,163.17,0.06,0.01,"1,723.32",10.16,264.53,0.39,0.03,"3,217.08",104.34
9,GRAY,0.06,0.06,172.45,0.41,0.01,"11,907.20",71.44,329.09,0.64,0.04,"5,285.44",211.96
10,GREEN,0.01,0.01,183.80,0.19,0.01,"4,216.46",35.73,274.71,0.70,0.04,"4,304.65",191.53
11,LIGHT BLUE,0.00,0.00,128.06,0.77,0.09,"1,038.22",98.44,200.40,8.16,0.09,"17,243.00","1,634.88"
12,LIGHT BROWN,0.00,0.00,89.76,0.00,0.00,NaN,0.00,115.47,0.00,0.00,NaN,0.00
13,LIGHT GRAY,0.00,0.00,137.90,0.00,0.00,NaN,0.00,287.85,0.00,0.00,NaN,0.00
14,MAROON,0.00,0.00,167.62,0.00,0.00,NaN,0.00,278.62,0.35,0.05,"2,027.15",97.08
15,OFF WHITE,0.00,0.00,220.07,0.00,0.00,NaN,0.00,314.15,0.00,0.00,NaN,0.00
16,ORANGE,0.00,0.00,168.28,0.21,0.01,"2,872.03",35.22,323.34,0.83,0.06,"4,888.53",269.79
17,PURPLE,0.00,0.00,181.37,1.80,0.02,"20,000.00",325.72,317.65,0.61,0.05,"3,947.77",192.88
18,RED,0.06,0.06,164.03,0.54,0.01,"17,705.06",88.85,306.42,0.50,0.04,"3,827.83",152.54
19,SILVER,0.06,0.06,176.74,0.52,0.01,"13,544.65",92.62,315.94,0.41,0.04,"3,250.58",130.71
20,TAN,0.00,0.00,154.76,0.00,0.00,NaN,0.00,209.21,0.36,0.02,"4,825.72",75.67
21,WHITE,0.07,0.07,175.66,0.28,0.00,"11,557.44",48.83,335.34,0.53,0.04,"3,916.04",176.15
22,YELLOW,0.00,0.00,165.60,0.00,0.00,NaN,0.00,262.95,0.36,0.06,"1,637.11",93.35
23,NaN,0.56,0.56,172.67,0.57,0.01,"16,448.17",97.71,252.10,0.46,0.03,"3,490.80",115.33

-------------------------------------------------------------------------------------------------------------------------------------------------

,color_interior,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,BEIGE,0.02,0.02,164.94,0.31,0.00,"10,661.22",51.05,298.12,0.43,0.04,"3,650.94",128.20
1,BLACK,0.26,0.26,173.42,0.52,0.01,"14,192.04",90.68,341.26,0.56,0.04,"4,451.69",192.51
2,BLUE,0.00,0.00,197.57,0.00,0.00,NaN,0.00,377.07,0.16,0.03,"1,790.16",59.98
3,BROWN,0.01,0.01,170.13,0.30,0.01,"8,684.59",50.79,333.73,0.35,0.02,"5,024.94",117.56
4,DARK BLUE,0.00,0.00,73.11,0.00,0.00,NaN,0.00,287.43,2.59,1.00,743.48,744.59
5,DARK BROWN,0.00,0.00,124.29,0.00,0.00,NaN,0.00,153.07,0.00,0.00,NaN,0.00
6,DARK GRAY,0.02,0.02,189.95,0.48,0.01,"16,587.59",91.86,268.48,0.38,0.03,"3,109.62",103.33
7,GOLD,0.00,0.00,171.07,0.00,0.00,NaN,0.00,317.79,0.19,0.03,"2,178.12",61.80
8,GRAY,0.11,0.11,176.41,0.71,0.01,"19,749.48",125.14,294.04,0.46,0.04,"3,347.56",135.42
9,GREEN,0.00,0.00,201.51,0.00,0.00,NaN,0.00,215.58,0.00,0.00,NaN,0.00
10,LIGHT BLUE,0.00,0.00,143.83,0.00,0.00,NaN,0.00,279.36,1.82,0.17,"3,059.47",509.55
11,LIGHT BROWN,0.00,0.00,154.66,0.00,0.00,NaN,0.00,220.78,0.00,0.00,NaN,0.00
12,LIGHT GRAY,0.00,0.00,160.38,0.10,0.00,"4,350.00",15.77,243.07,0.60,0.03,"5,713.37",144.97
13,MAROON,0.00,0.00,191.94,0.00,0.00,NaN,0.00,462.63,0.00,0.00,NaN,0.00
14,OFF WHITE,0.00,0.00,131.03,0.00,0.00,NaN,0.00,171.01,0.00,0.00,NaN,0.00
15,ORANGE,0.00,0.00,262.44,0.00,0.00,NaN,0.00,296.85,0.00,0.00,NaN,0.00
16,PINK,0.00,0.00,92.41,0.00,0.00,NaN,0.00,210.22,0.00,0.00,NaN,0.00
17,RED,0.00,0.00,182.07,0.00,0.00,NaN,0.00,389.76,0.12,0.03,"1,479.13",46.44
18,SILVER,0.00,0.00,194.16,0.00,0.00,NaN,0.00,327.07,0.29,0.05,"1,907.86",96.28
19,TAN,0.02,0.02,175.69,0.17,0.01,"4,756.46",29.98,299.18,0.46,0.03,"4,532.90",138.78
20,WHITE,0.01,0.01,165.27,0.12,0.00,"6,800.00",19.72,327.27,0.51,0.05,"3,562.53",165.34
21,YELLOW,0.00,0.00,128.94,0.00,0.00,NaN,0.00,333.89,0.00,0.00,NaN,0.00
22,NaN,0.54,0.54,173.41,0.62,0.01,"18,750.98",107.74,253.40,0.45,0.03,"3,376.66",114.85

-------------------------------------------------------------------------------------------------------------------------------------------------

,year_CEF,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,"1,981.00",0.00,0.00,80.14,0.00,0.00,NaN,0.00,20.80,0.00,0.00,NaN,0.00
1,"1,982.00",0.00,0.00,124.37,0.00,0.00,NaN,0.00,84.31,0.00,0.00,NaN,0.00
2,"1,983.00",0.00,0.00,70.38,0.00,0.00,NaN,0.00,29.90,0.00,0.00,NaN,0.00
3,"1,984.00",0.00,0.00,91.50,0.00,0.00,NaN,0.00,52.56,0.00,0.00,NaN,0.00
4,"1,985.00",0.00,0.00,74.61,0.00,0.00,NaN,0.00,60.95,0.00,0.00,NaN,0.00
5,"1,986.00",0.00,0.00,84.05,0.00,0.00,NaN,0.00,40.16,0.00,0.00,NaN,0.00
6,"1,987.00",0.00,0.00,166.97,0.00,0.00,NaN,0.00,63.62,0.00,0.00,NaN,0.00
7,"1,988.00",0.00,0.00,122.03,0.00,0.00,NaN,0.00,58.52,0.00,0.00,NaN,0.00
8,"1,989.00",0.00,0.00,99.30,0.07,0.03,245.70,6.78,69.19,0.00,0.00,NaN,0.00
9,"1,990.00",0.00,0.00,110.20,0.00,0.00,NaN,0.00,65.59,0.00,0.00,NaN,0.00
10,"1,991.00",0.00,0.00,110.73,0.00,0.00,NaN,0.00,75.88,0.62,0.02,"2,474.00",46.94
11,"1,992.00",0.00,0.00,141.87,0.00,0.00,NaN,0.00,85.63,0.30,0.02,"1,638.00",25.78
12,"1,993.00",0.00,0.00,124.53,0.00,0.00,NaN,0.00,92.46,0.33,0.01,"2,671.65",30.76
13,"1,994.00",0.00,0.00,116.82,0.00,0.00,NaN,0.00,89.97,0.24,0.01,"3,418.00",21.76
14,"1,995.00",0.00,0.00,158.92,0.00,0.00,NaN,0.00,116.44,0.03,0.01,306.77,3.11
15,"1,996.00",0.00,0.00,136.11,0.00,0.00,NaN,0.00,125.65,0.09,0.01,"1,215.36",11.47
16,"1,997.00",0.01,0.01,160.03,0.17,0.00,"9,000.00",27.27,140.79,0.09,0.01,"1,033.42",12.52
17,"1,998.00",0.01,0.01,160.66,0.13,0.00,"9,039.52",20.89,149.27,0.07,0.01,"1,194.63",11.04
18,"1,999.00",0.01,0.01,156.14,0.45,0.00,"15,021.02",70.70,154.75,0.15,0.01,"1,697.65",23.97
19,"2,000.00",0.02,0.02,166.20,0.25,0.00,"10,113.07",41.48,163.40,0.20,0.01,"2,447.04",32.62
20,"2,001.00",0.02,0.02,156.09,0.03,0.00,"5,558.60",5.13,180.70,0.30,0.02,"2,168.67",54.08
21,"2,002.00",0.03,0.03,173.88,0.94,0.01,"30,913.24",162.90,190.40,0.26,0.02,"2,316.93",50.36
22,"2,003.00",0.04,0.04,174.23,0.80,0.01,"25,158.93",139.35,193.73,0.41,0.03,"2,986.07",79.69
23,"2,004.00",0.04,0.04,181.31,0.61,0.01,"16,619.87",110.80,217.89,0.40,0.03,"2,646.46",88.22
24,"2,005.00",0.05,0.05,174.29,1.01,0.01,"22,780.90",176.55,221.80,0.37,0.03,"2,538.87",81.65
25,"2,006.00",0.05,0.05,183.01,0.37,0.01,"12,978.52",67.28,247.30,0.34,0.03,"2,849.26",83.35
26,"2,007.00",0.05,0.05,192.27,0.85,0.01,"15,559.61",162.80,259.75,0.47,0.04,"3,191.73",122.81
27,"2,008.00",0.06,0.06,182.34,0.35,0.01,"11,268.23",64.67,260.85,0.40,0.03,"3,110.58",104.30
28,"2,009.00",0.04,0.04,190.35,0.24,0.01,"7,514.78",45.01,282.07,0.42,0.04,"3,319.46",119.30
29,"2,010.00",0.05,0.05,189.39,0.32,0.00,"15,638.88",61.33,295.25,0.46,0.03,"3,915.62",135.41
30,"2,011.00",0.06,0.06,181.53,0.55,0.01,"17,728.69",100.70,289.54,0.40,0.04,"3,001.47",115.55
31,"2,012.00",0.06,0.06,183.57,0.35,0.01,"10,405.15",63.59,327.50,0.56,0.05,"3,568.97",183.84
32,"2,013.00",0.07,0.07,172.56,0.61,0.01,"17,491.55",105.50,324.12,0.59,0.05,"4,125.56",191.49
33,"2,014.00",0.07,0.07,180.41,0.32,0.01,"8,550.26",57.31,349.62,0.47,0.04,"3,863.60",162.77
34,"2,015.00",0.08,0.08,172.52,0.72,0.01,"19,960.32",123.71,362.44,0.69,0.04,"5,650.19",251.62
35,"2,016.00",0.06,0.06,171.02,1.63,0.00,"63,353.41",279.27,368.62,0.48,0.04,"4,166.78",175.11
36,"2,017.00",0.05,0.05,165.71,0.59,0.01,"13,194.31",98.12,373.67,0.61,0.05,"4,702.95",226.40
37,"2,018.00",0.03,0.03,158.79,0.35,0.01,"7,825.21",56.00,366.50,0.70,0.05,"4,713.33",257.58
38,"2,019.00",0.01,0.01,135.26,0.20,0.00,"7,141.67",27.02,324.28,0.29,0.03,"3,068.73",92.90
39,"2,020.00",0.00,0.00,76.58,0.00,0.00,NaN,0.00,210.56,1.17,0.03,"8,744.62",246.17
40,"2,021.00",0.00,0.00,12.23,0.00,0.00,NaN,0.00,39.09,0.00,0.00,NaN,0.00
41,NaN,0.04,0.04,132.56,0.39,0.01,"7,946.71",51.27,240.49,0.47,0.03,"3,448.94",112.85

-------------------------------------------------------------------------------------------------------------------------------------------------

,mDrvGenMarSts,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,FM,0.28,0.28,156.04,0.53,0.00,"18,534.71",82.51,256.95,0.45,0.03,"3,351.17",116.36
1,FS,0.18,0.18,200.43,0.58,0.01,"16,729.74",115.51,322.64,0.44,0.04,"3,337.30",140.85
2,MM,0.34,0.34,156.78,0.44,0.01,"13,198.04",69.19,264.93,0.45,0.03,"3,568.54",119.09
3,MS,0.16,0.16,207.28,0.81,0.01,"21,039.57",168.93,328.37,0.63,0.04,"5,054.76",206.93
4,NaN,0.04,0.04,189.94,0.71,0.01,"15,983.51",134.29,304.64,0.55,0.04,"3,798.15",167.53

-------------------------------------------------------------------------------------------------------------------------------------------------

,modelyear,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,"1,949.00",0.00,0.00,28.27,0.00,0.00,NaN,0.00,18.18,0.00,0.00,NaN,0.00
1,"1,952.00",0.00,0.00,95.86,0.00,0.00,NaN,0.00,63.57,0.00,0.00,NaN,0.00
2,"1,964.00",0.00,0.00,39.89,0.00,0.00,NaN,0.00,49.86,0.00,0.00,NaN,0.00
3,"1,965.00",0.00,0.00,68.25,0.00,0.00,NaN,0.00,33.21,0.00,0.00,NaN,0.00
4,"1,967.00",0.00,0.00,29.14,0.00,0.00,NaN,0.00,76.44,0.00,0.00,NaN,0.00
5,"1,968.00",0.00,0.00,37.01,0.00,0.00,NaN,0.00,13.00,0.00,0.00,NaN,0.00
6,"1,969.00",0.00,0.00,40.43,0.00,0.00,NaN,0.00,82.82,0.00,0.00,NaN,0.00
7,"1,971.00",0.00,0.00,82.69,0.00,0.00,NaN,0.00,55.13,0.00,0.00,NaN,0.00
8,"1,973.00",0.00,0.00,55.14,0.00,0.00,NaN,0.00,46.37,0.00,0.00,NaN,0.00
9,"1,974.00",0.00,0.00,130.91,0.00,0.00,NaN,0.00,87.89,0.00,0.00,NaN,0.00
10,"1,976.00",0.00,0.00,69.43,0.00,0.00,NaN,0.00,51.58,0.00,0.00,NaN,0.00
11,"1,977.00",0.00,0.00,99.18,0.00,0.00,NaN,0.00,23.80,0.00,0.00,NaN,0.00
12,"1,978.00",0.00,0.00,100.01,0.00,0.00,NaN,0.00,38.00,0.00,0.00,NaN,0.00
13,"1,979.00",0.00,0.00,247.18,0.00,0.00,NaN,0.00,182.87,0.00,0.00,NaN,0.00
14,"1,981.00",0.00,0.00,76.58,0.00,0.00,NaN,0.00,18.99,0.00,0.00,NaN,0.00
15,"1,982.00",0.00,0.00,124.37,0.00,0.00,NaN,0.00,84.31,0.00,0.00,NaN,0.00
16,"1,983.00",0.00,0.00,70.38,0.00,0.00,NaN,0.00,29.90,0.00,0.00,NaN,0.00
17,"1,984.00",0.00,0.00,91.50,0.00,0.00,NaN,0.00,52.56,0.00,0.00,NaN,0.00
18,"1,985.00",0.00,0.00,74.28,0.00,0.00,NaN,0.00,60.28,0.00,0.00,NaN,0.00
19,"1,986.00",0.00,0.00,99.83,0.00,0.00,NaN,0.00,52.55,0.00,0.00,NaN,0.00
20,"1,987.00",0.00,0.00,155.98,0.00,0.00,NaN,0.00,59.07,0.00,0.00,NaN,0.00
21,"1,988.00",0.00,0.00,122.03,0.00,0.00,NaN,0.00,58.52,0.00,0.00,NaN,0.00
22,"1,989.00",0.00,0.00,99.30,0.07,0.03,245.70,6.78,69.19,0.00,0.00,NaN,0.00
23,"1,990.00",0.00,0.00,110.66,0.00,0.00,NaN,0.00,66.89,0.00,0.00,NaN,0.00
24,"1,991.00",0.00,0.00,110.73,0.00,0.00,NaN,0.00,75.88,0.62,0.02,"2,474.00",46.94
25,"1,992.00",0.00,0.00,140.49,0.00,0.00,NaN,0.00,84.79,0.30,0.02,"1,638.00",25.38
26,"1,993.00",0.00,0.00,124.55,0.00,0.00,NaN,0.00,92.98,0.33,0.01,"2,671.65",30.37
27,"1,994.00",0.00,0.00,115.98,0.00,0.00,NaN,0.00,90.24,0.24,0.01,"3,418.00",21.37
28,"1,995.00",0.00,0.00,156.63,0.00,0.00,NaN,0.00,115.15,0.03,0.01,306.77,3.04
29,"1,996.00",0.00,0.00,135.41,0.00,0.00,NaN,0.00,125.69,0.09,0.01,"1,215.36",11.19
30,"1,997.00",0.01,0.01,156.32,0.17,0.00,"9,000.00",26.06,138.12,0.09,0.01,"1,033.42",11.97
31,"1,998.00",0.01,0.01,159.06,0.13,0.00,"9,039.52",20.13,148.87,0.07,0.01,"1,194.63",10.64
32,"1,999.00",0.01,0.01,154.51,0.45,0.00,"15,021.02",68.88,153.70,0.15,0.01,"1,697.65",23.35
33,"2,000.00",0.02,0.02,164.23,0.25,0.00,"10,113.07",40.28,162.01,0.20,0.01,"2,447.04",31.68
34,"2,001.00",0.02,0.02,156.13,0.08,0.00,"7,129.30",12.89,181.64,0.30,0.03,"2,098.63",55.02
35,"2,002.00",0.03,0.03,171.80,0.92,0.01,"27,666.66",157.70,189.96,0.30,0.02,"2,286.24",56.47
36,"2,003.00",0.04,0.04,173.29,0.78,0.01,"25,158.93",135.73,193.18,0.42,0.03,"2,985.42",80.53
37,"2,004.00",0.04,0.04,179.93,0.65,0.01,"16,831.13",116.44,217.74,0.41,0.03,"2,655.92",88.43
38,"2,005.00",0.05,0.05,172.29,0.99,0.01,"22,780.90",170.41,220.12,0.36,0.03,"2,509.38",78.84
39,"2,006.00",0.05,0.05,181.06,0.38,0.01,"12,746.61",68.56,246.49,0.38,0.03,"3,162.23",94.12
40,"2,007.00",0.05,0.05,190.17,0.85,0.01,"15,376.50",160.97,258.61,0.47,0.04,"3,169.96",121.33
41,"2,008.00",0.06,0.06,181.55,0.36,0.01,"10,943.03",64.73,260.84,0.40,0.03,"3,115.85",104.14
42,"2,009.00",0.04,0.04,188.96,0.23,0.01,"7,514.78",44.12,281.40,0.45,0.04,"3,481.49",125.55
43,"2,010.00",0.05,0.05,187.25,0.34,0.00,"13,086.01",63.36,294.37,0.48,0.04,"3,935.99",140.21
44,"2,011.00",0.06,0.06,178.85,0.55,0.01,"17,728.69",97.52,287.21,0.39,0.04,"3,001.47",111.90
45,"2,012.00",0.06,0.06,181.76,0.35,0.01,"10,055.45",62.76,326.35,0.55,0.05,"3,518.19",180.66
46,"2,013.00",0.07,0.07,170.78,0.63,0.01,"17,533.57",107.55,322.60,0.58,0.05,"4,099.55",188.61
47,"2,014.00",0.08,0.08,178.45,0.32,0.01,"8,295.46",56.31,347.59,0.47,0.04,"3,862.25",162.72
48,"2,015.00",0.08,0.08,169.63,0.71,0.01,"19,960.32",119.61,358.31,0.69,0.04,"5,516.11",247.30
49,"2,016.00",0.06,0.06,169.11,1.61,0.00,"63,353.41",272.07,365.06,0.48,0.04,"4,187.43",176.23
50,"2,017.00",0.05,0.05,164.96,0.58,0.01,"13,194.31",96.37,373.14,0.60,0.05,"4,678.99",223.04
51,"2,018.00",0.03,0.03,157.23,0.35,0.01,"7,825.21",55.00,363.69,0.70,0.05,"4,713.33",252.97
52,"2,019.00",0.01,0.01,134.96,0.20,0.00,"7,141.67",26.94,323.57,0.29,0.03,"3,068.73",92.62
53,"2,020.00",0.00,0.00,76.58,0.00,0.00,NaN,0.00,210.56,1.17,0.03,"8,744.62",246.17
54,"2,021.00",0.00,0.00,12.23,0.00,0.00,NaN,0.00,39.09,0.00,0.00,NaN,0.00
55,NaN,0.01,0.01,183.90,0.19,0.00,"11,673.28",34.94,277.48,0.29,0.03,"3,112.81",79.20

-------------------------------------------------------------------------------------------------------------------------------------------------

,rand,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,0.00,0.00,0.00,81.33,0.00,0.00,NaN,0.00,126.96,0.00,0.00,NaN,0.00
1,0.00,0.00,0.00,239.16,0.00,0.00,NaN,0.00,244.03,0.00,0.00,NaN,0.00
2,0.00,0.00,0.00,222.00,0.00,0.00,NaN,0.00,244.98,0.00,0.00,NaN,0.00
3,0.00,0.00,0.00,571.04,0.00,0.00,NaN,0.00,735.33,0.00,0.00,NaN,0.00
4,0.00,0.00,0.00,172.16,0.00,0.00,NaN,0.00,210.20,24.24,1.98,"2,579.58","5,095.69"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15903,0.02,0.00,0.00,106.29,0.00,0.00,NaN,0.00,160.44,0.00,0.00,NaN,0.00
15904,0.02,0.00,0.00,89.79,0.00,0.00,NaN,0.00,393.77,0.00,0.00,NaN,0.00
15905,0.02,0.00,0.00,161.49,0.00,0.00,NaN,0.00,129.69,4.53,0.17,"3,527.91",587.34
15906,0.02,0.00,0.00,84.34,0.00,0.00,NaN,0.00,134.54,0.00,0.00,NaN,0.00
15907,0.02,0.00,0.00,139.62,0.00,0.00,NaN,0.00,293.20,0.00,0.00,NaN,0.00

-------------------------------------------------------------------------------------------------------------------------------------------------

,zip,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,"43,001.00",0.00,0.00,139.22,0.00,0.00,NaN,0.00,175.65,0.00,0.00,NaN,0.00
1,"43,003.00",0.00,0.00,90.18,0.00,0.00,NaN,0.00,193.11,0.00,0.00,NaN,0.00
2,"43,004.00",0.00,0.00,180.44,0.00,0.00,NaN,0.00,313.69,0.00,0.00,NaN,0.00
3,"43,006.00",0.00,0.00,206.54,0.00,0.00,NaN,0.00,352.47,0.05,0.02,"1,115.05",16.96
4,"43,008.00",0.00,0.00,88.77,0.00,0.00,NaN,0.00,246.97,0.00,0.00,NaN,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1056,"45,891.00",0.00,0.00,125.97,0.00,0.00,NaN,0.00,186.35,0.00,0.00,NaN,0.00
1057,"45,894.00",0.00,0.00,156.75,0.00,0.00,NaN,0.00,278.97,0.21,0.04,"1,684.81",59.36
1058,"45,895.00",0.00,0.00,81.17,0.00,0.00,NaN,0.00,80.73,4.24,0.13,"2,737.71",342.35
1059,"45,896.00",0.00,0.00,112.62,0.00,0.00,NaN,0.00,217.16,0.18,0.02,"2,410.02",38.88
1060,"45,898.00",0.00,0.00,94.28,0.00,0.00,NaN,0.00,135.79,0.00,0.00,NaN,0.00

-------------------------------------------------------------------------------------------------------------------------------------------------

,pol_id,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,0,0.00,0.00,196.03,0.00,0.00,NaN,0.00,391.09,0.00,0.00,NaN,0.00
1,1,0.00,0.00,238.55,0.00,0.00,NaN,0.00,"1,333.55",0.00,0.00,NaN,0.00
2,2,0.00,0.00,113.20,0.00,0.00,NaN,0.00,164.66,0.00,0.00,NaN,0.00
3,3,0.00,0.00,206.14,0.00,0.00,NaN,0.00,350.07,0.00,0.00,NaN,0.00
4,4,0.00,0.00,160.97,0.00,0.00,NaN,0.00,426.63,0.00,0.00,NaN,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15906,15906,0.00,0.00,113.02,0.00,0.00,NaN,0.00,199.04,0.00,0.00,NaN,0.00
15907,15907,0.00,0.00,52.94,0.00,0.00,NaN,0.00,53.94,0.00,0.00,NaN,0.00
15908,15908,0.00,0.00,207.00,0.00,0.00,NaN,0.00,235.00,0.00,0.00,NaN,0.00
15909,15909,0.00,0.00,157.21,0.00,0.00,NaN,0.00,315.79,0.00,0.00,NaN,0.00
15910,15910,0.00,0.00,230.11,0.00,0.00,NaN,0.00,277.72,0.00,0.00,NaN,0.00

-------------------------------------------------------------------------------------------------------------------------------------------------

,vin_id,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,0,0.00,0.00,198.39,0.00,0.00,NaN,0.00,393.76,0.00,0.00,NaN,0.00
1,1,0.00,0.00,140.29,0.00,0.00,NaN,0.00,328.03,0.00,0.00,NaN,0.00
2,2,0.00,0.00,238.55,0.00,0.00,NaN,0.00,"1,333.55",0.00,0.00,NaN,0.00
3,3,0.00,0.00,130.72,0.00,0.00,NaN,0.00,163.28,0.00,0.00,NaN,0.00
4,4,0.00,0.00,60.62,0.00,0.00,NaN,0.00,168.77,0.00,0.00,NaN,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
34520,34520,0.00,0.00,113.02,0.00,0.00,NaN,0.00,199.04,0.00,0.00,NaN,0.00
34521,34521,0.00,0.00,52.94,0.00,0.00,NaN,0.00,53.94,0.00,0.00,NaN,0.00
34522,34522,0.00,0.00,207.00,0.00,0.00,NaN,0.00,235.00,0.00,0.00,NaN,0.00
34523,34523,0.00,0.00,224.28,0.00,0.00,NaN,0.00,360.60,0.00,0.00,NaN,0.00
34524,34524,0.00,0.00,178.53,0.00,0.00,NaN,0.00,286.64,0.00,0.00,NaN,0.00

-------------------------------------------------------------------------------------------------------------------------------------------------

### Create function that drop duplicates and returns the number of unique rows.

In [ ]:
def unique_non_null(data,field):
    a = data.loc[data[field].isna() == False][([field])].drop_duplicates()
    return a.shape[0]

unique_non_null(data1,'cbistier')

13

### Create an empty dataframe named useless_fields

### Loop through columns in data1, determine and print which fields are useless, and add those fields that have 1 or less rows to useless_fields dataframe

In [ ]:
useless_fields = []

for j in [i for i in data1.columns if i not in facts]:
    if unique_non_null(data1,j) <= 1:
        print(j + ' has 1 or less rows')
        useless_fields.append(j)

insstate has 1 or less rows
make has 1 or less rows
model has 1 or less rows

### Check shape of data1 before and after dropping useless_fields to ensure it was done correctly

#### How does this ensure that we have removed the fields correctly?

In [ ]:
print(data1.shape)
data1.drop(columns = useless_fields, inplace = True)
print(data1.shape)

(100443, 35)
(100443, 32)

## Group feature levels as new features in dataset

### Below we will use the function now to perform EDA on this dataset

### Use a list comprehension to determine which fields to analyze

In [ ]:
stuff_to_analyze = [i for i in data1.columns if i not in facts]
stuff_to_analyze

['cbistier',
 'vehuse',
 'numveh',
 'numdrv',
 'modlyr',
 'collsymb',
 'perslimbi',
 'acclimbi',
 'deductiblecol',
 'pol_eff_date',
 'pol_exp_date',
 'pol_eff_year',
 'DrvAge',
 'DrvSex',
 'DrvMarSts',
 'color_exterior',
 'color_interior',
 'year_CEF',
 'mDrvGenMarSts',
 'modelyear',
 'rand',
 'zip',
 'pol_id',
 'vin_id']

### Use eda_table function to assess cbistier

In [ ]:
eda_table(data1,'cbistier')

,cbistier,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,0,0.01,0.01,179.00,0.28,0.00,"11,032.33",50.99,286.54,0.45,0.04,"3,184.47",127.55
1,1,0.10,0.10,144.21,1.11,0.00,"39,083.38",160.06,226.02,0.33,0.03,"2,821.43",73.66
2,2,0.12,0.12,140.92,0.28,0.00,"13,762.89",39.36,222.45,0.30,0.03,"2,487.89",67.24
3,3,0.12,0.12,154.11,0.55,0.00,"16,933.24",84.05,243.70,0.43,0.03,"3,663.73",104.70
4,4,0.11,0.11,168.87,0.48,0.01,"13,264.04",81.42,264.13,0.52,0.03,"3,972.33",137.96
5,5,0.11,0.11,169.29,0.41,0.01,"12,125.62",70.01,273.29,0.42,0.04,"3,251.71",114.73
6,6,0.10,0.10,177.45,0.71,0.01,"22,458.52",125.19,293.38,0.50,0.04,"3,952.96",147.56
7,7,0.10,0.10,188.78,0.27,0.01,"7,778.69",51.80,314.05,0.49,0.04,"3,693.59",154.06
8,8,0.09,0.09,199.43,0.45,0.01,"11,350.42",90.13,336.54,0.52,0.04,"3,909.51",174.62
9,9,0.07,0.07,219.17,1.19,0.01,"23,075.94",260.69,370.77,0.84,0.06,"5,350.50",312.52
10,10,0.05,0.05,228.59,0.47,0.01,"14,795.56",106.72,423.79,0.47,0.06,"3,581.19",198.04
11,90,0.00,0.00,215.27,0.00,0.00,NaN,0.00,388.41,0.77,0.05,"5,841.59",299.08
12,99,0.00,0.00,194.30,0.00,0.00,NaN,0.00,290.14,0.35,0.04,"2,331.87",102.29

### 90 and 99 are no hit/no score - let's put them in with the "base level" and call them 5.  Let's also rename this field.

#### How can we tell that the field is renamed? Does cbistier still exist at this time?

In [ ]:
data1['credit'] = np.where(data1['cbistier'] > 10, 5, data1['cbistier'])

eda_table(data1,'credit')

,credit,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,0,0.01,0.01,179.00,0.28,0.00,"11,032.33",50.99,286.54,0.45,0.04,"3,184.47",127.55
1,1,0.10,0.10,144.21,1.11,0.00,"39,083.38",160.06,226.02,0.33,0.03,"2,821.43",73.66
2,2,0.12,0.12,140.92,0.28,0.00,"13,762.89",39.36,222.45,0.30,0.03,"2,487.89",67.24
3,3,0.12,0.12,154.11,0.55,0.00,"16,933.24",84.05,243.70,0.43,0.03,"3,663.73",104.70
4,4,0.11,0.11,168.87,0.48,0.01,"13,264.04",81.42,264.13,0.52,0.03,"3,972.33",137.96
5,5,0.11,0.11,170.40,0.40,0.01,"12,125.62",67.99,275.57,0.43,0.04,"3,307.52",117.96
6,6,0.10,0.10,177.45,0.71,0.01,"22,458.52",125.19,293.38,0.50,0.04,"3,952.96",147.56
7,7,0.10,0.10,188.78,0.27,0.01,"7,778.69",51.80,314.05,0.49,0.04,"3,693.59",154.06
8,8,0.09,0.09,199.43,0.45,0.01,"11,350.42",90.13,336.54,0.52,0.04,"3,909.51",174.62
9,9,0.07,0.07,219.17,1.19,0.01,"23,075.94",260.69,370.77,0.84,0.06,"5,350.50",312.52
10,10,0.05,0.05,228.59,0.47,0.01,"14,795.56",106.72,423.79,0.47,0.06,"3,581.19",198.04

### Create a blank list named remove_list
### Add cbistier to remove_list
### Use remove() to cbistier from stuff_to_analyze

In [ ]:
remove_list = []
remove_list.append('cbistier')

stuff_to_analyze.remove('cbistier')

### View fields that still need to be analyzed

In [ ]:
stuff_to_analyze

['vehuse',
 'numveh',
 'numdrv',
 'modlyr',
 'collsymb',
 'perslimbi',
 'acclimbi',
 'deductiblecol',
 'pol_eff_date',
 'pol_exp_date',
 'pol_eff_year',
 'DrvAge',
 'DrvSex',
 'DrvMarSts',
 'color_exterior',
 'color_interior',
 'year_CEF',
 'mDrvGenMarSts',
 'modelyear',
 'rand',
 'zip',
 'pol_id',
 'vin_id']

### Use eda_table function to assess vehuse

In [ ]:
eda_table(data1,'vehuse')

,vehuse,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,B,0.00,0.00,228.34,0.41,0.01,"7,973.67",93.12,278.71,0.77,0.04,"5,018.26",214.90
1,C,0.42,0.42,186.90,0.60,0.01,"18,058.02",112.77,303.03,0.51,0.04,"4,009.36",155.48
2,F,0.01,0.01,125.78,0.00,0.00,NaN,0.00,195.25,0.29,0.01,"5,082.01",55.87
3,P,0.53,0.53,167.04,0.56,0.01,"16,963.67",92.81,274.13,0.45,0.04,"3,436.54",123.36
4,W,0.03,0.03,126.27,0.66,0.01,"9,132.68",82.82,254.17,0.70,0.04,"4,361.10",177.96
5,NaN,0.00,0.00,136.08,0.31,0.01,"3,525.00",42.38,291.69,0.29,0.03,"2,846.00",85.55

### Since Business and Farm are such low exposures, let's ignore those
### Let's assume W is a data issue and stands for 'Work' and make a flag for C & W and call it commute_flag
### Add vehuse to remove_list and remove it from stuff_to_analyze

In [ ]:
data1['commute_flag'] = np.where(data1['vehuse'].isin(['C','W']) == True, True, False)
remove_list.append('vehuse')
stuff_to_analyze.remove('vehuse')

eda_table(data1,'commute_flag')

,commute_flag,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,False,0.55,0.55,166.53,0.54,0.01,"16,645.05",90.64,272.65,0.45,0.04,"3,460.17",122.53
1,True,0.45,0.45,182.70,0.61,0.01,"17,187.25",110.70,299.64,0.52,0.04,"4,034.92",157.04

### View fields that still need to be analyzed

In [ ]:
stuff_to_analyze

['numveh',
 'numdrv',
 'modlyr',
 'collsymb',
 'perslimbi',
 'acclimbi',
 'deductiblecol',
 'pol_eff_date',
 'pol_exp_date',
 'pol_eff_year',
 'DrvAge',
 'DrvSex',
 'DrvMarSts',
 'color_exterior',
 'color_interior',
 'year_CEF',
 'mDrvGenMarSts',
 'modelyear',
 'rand',
 'zip',
 'pol_id',
 'vin_id']

### Use eda_table function to assess numveh

In [ ]:
eda_table(data1,'numveh')

,numveh,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,1,0.21,0.21,210.25,0.43,0.01,"10,863.91",89.69,343.30,0.55,0.05,"3,914.62",188.97
1,2,0.39,0.39,154.86,0.62,0.01,"18,664.39",96.51,262.15,0.48,0.04,"3,453.64",125.95
2,3,0.23,0.23,165.70,0.48,0.01,"13,992.41",79.62,268.84,0.44,0.03,"3,731.40",117.48
3,4,0.11,0.11,187.66,0.43,0.01,"14,800.64",81.11,292.76,0.47,0.04,"3,854.98",137.93
4,5,0.04,0.04,184.69,1.95,0.01,"71,515.25",360.46,285.70,0.41,0.03,"4,502.96",117.61
5,6,0.01,0.01,156.31,0.92,0.00,"100,000.00",144.18,253.01,0.49,0.02,"6,613.43",123.96
6,7,0.00,0.00,179.04,0.00,0.00,NaN,0.00,281.68,0.10,0.01,"2,044.68",28.88
7,8,0.00,0.00,114.76,0.00,0.00,NaN,0.00,165.52,2.16,0.04,"9,470.99",356.87
8,9,0.00,0.00,138.04,0.00,0.00,NaN,0.00,189.48,0.00,0.00,NaN,0.00
9,10,0.00,0.00,82.68,0.00,0.00,NaN,0.00,145.19,0.00,0.00,NaN,0.00
10,11,0.00,0.00,60.50,0.00,0.00,NaN,0.00,109.03,0.00,0.00,NaN,0.00
11,12,0.00,0.00,148.00,0.00,0.00,NaN,0.00,147.33,0.00,0.00,NaN,0.00

### We're getting tired of repetitive tasks, let's make a function that creates a new field in the data with a suffix "_box" that will reduce the range of numeric fields

### Now that we have several examples above, guess what the cells below are attempting to do, run the cell, and determine whether you understood the code.

In [ ]:
def box_var(data, field, low, high, new_name = False):
    if new_name == False:
        data[field] = np.where(data[field] <= low, low, np.where(data[field] >= high, high, data[field]))
    else:
        data[new_name] = np.where(data[field] <= low, low, np.where(data[field] >= high, high, data[field]))

box_var(data1,'numveh',1,4, new_name = 'veh_count_box')

remove_list.append('numveh')
stuff_to_analyze.remove('numveh')

eda_table(data1,'veh_count_box')

,veh_count_box,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,1,0.21,0.21,210.25,0.43,0.01,"10,863.91",89.69,343.30,0.55,0.05,"3,914.62",188.97
1,2,0.39,0.39,154.86,0.62,0.01,"18,664.39",96.51,262.15,0.48,0.04,"3,453.64",125.95
2,3,0.23,0.23,165.70,0.48,0.01,"13,992.41",79.62,268.84,0.44,0.03,"3,731.40",117.48
3,4,0.17,0.17,183.68,0.80,0.00,"30,214.99",147.84,286.52,0.46,0.03,"4,137.57",131.16

In [ ]:
stuff_to_analyze

['numdrv',
 'modlyr',
 'collsymb',
 'perslimbi',
 'acclimbi',
 'deductiblecol',
 'pol_eff_date',
 'pol_exp_date',
 'pol_eff_year',
 'DrvAge',
 'DrvSex',
 'DrvMarSts',
 'color_exterior',
 'color_interior',
 'year_CEF',
 'mDrvGenMarSts',
 'modelyear',
 'rand',
 'zip',
 'pol_id',
 'vin_id']

In [ ]:
eda_table(data1,'numdrv')

,numdrv,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,1.00,0.22,0.22,179.51,0.72,0.01,"19,141.10",129.09,302.01,0.60,0.04,"4,221.33",180.53
1,2.00,0.53,0.53,143.39,0.35,0.00,"10,658.36",50.36,244.94,0.47,0.03,"3,397.61",115.00
2,3.00,0.15,0.15,210.01,0.88,0.01,"26,052.91",185.31,328.86,0.44,0.04,"3,812.81",143.16
3,4.00,0.08,0.08,260.32,0.69,0.01,"20,205.85",179.95,388.57,0.42,0.04,"4,042.77",162.48
4,5.00,0.02,0.02,325.27,0.42,0.01,"19,940.88",135.50,428.47,0.30,0.04,"3,192.44",126.55
5,6.00,0.00,0.00,264.64,0.16,0.01,"5,000.00",42.30,394.72,0.30,0.04,"2,787.59",117.90
6,7.00,0.00,0.00,325.08,0.00,0.00,NaN,0.00,359.93,0.00,0.00,NaN,0.00
7,9.00,0.00,0.00,66.10,0.00,0.00,NaN,0.00,150.57,0.00,0.00,NaN,0.00
8,10.00,0.00,0.00,83.78,0.00,0.00,NaN,0.00,150.53,0.00,0.00,NaN,0.00
9,11.00,0.00,0.00,78.37,0.00,0.00,NaN,0.00,155.45,0.00,0.00,NaN,0.00
10,13.00,0.00,0.00,132.01,0.00,0.00,NaN,0.00,600.42,0.00,0.00,NaN,0.00
11,NaN,0.00,0.00,127.77,0.00,0.00,NaN,0.00,274.95,2.28,0.06,"9,840.45",625.79

### We need to fill in the null value. Let's make a function which uses the modal value unless otherwise specified

In [ ]:
def fillna(data, field, new_name, specific_value = False):
    if specific_value == False:
        data[new_name] = data[field].fillna(data[field].mode().values[0])
    else:
        data[new_name] = data[field].fillna(specific_value)

fillna(data1, 'numdrv', 'numdrv2')

eda_table(data1,'numdrv2')

,numdrv2,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,1.00,0.22,0.22,179.51,0.72,0.01,"19,141.10",129.09,302.01,0.60,0.04,"4,221.33",180.53
1,2.00,0.53,0.53,143.37,0.35,0.00,"10,658.36",50.28,244.99,0.47,0.03,"3,416.69",115.80
2,3.00,0.15,0.15,210.01,0.88,0.01,"26,052.91",185.31,328.86,0.44,0.04,"3,812.81",143.16
3,4.00,0.08,0.08,260.32,0.69,0.01,"20,205.85",179.95,388.57,0.42,0.04,"4,042.77",162.48
4,5.00,0.02,0.02,325.27,0.42,0.01,"19,940.88",135.50,428.47,0.30,0.04,"3,192.44",126.55
5,6.00,0.00,0.00,264.64,0.16,0.01,"5,000.00",42.30,394.72,0.30,0.04,"2,787.59",117.90
6,7.00,0.00,0.00,325.08,0.00,0.00,NaN,0.00,359.93,0.00,0.00,NaN,0.00
7,9.00,0.00,0.00,66.10,0.00,0.00,NaN,0.00,150.57,0.00,0.00,NaN,0.00
8,10.00,0.00,0.00,83.78,0.00,0.00,NaN,0.00,150.53,0.00,0.00,NaN,0.00
9,11.00,0.00,0.00,78.37,0.00,0.00,NaN,0.00,155.45,0.00,0.00,NaN,0.00
10,13.00,0.00,0.00,132.01,0.00,0.00,NaN,0.00,600.42,0.00,0.00,NaN,0.00

In [ ]:
box_var(data1,'numdrv2',1,4, new_name = 'driver_count_box')

remove_list.append('numdrv')
remove_list.append('numdrv2')

stuff_to_analyze.remove('numdrv')

eda_table(data1,'driver_count_box')

,driver_count_box,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,1.00,0.22,0.22,179.51,0.72,0.01,"19,141.10",129.09,302.01,0.60,0.04,"4,221.33",180.53
1,2.00,0.53,0.53,143.37,0.35,0.00,"10,658.36",50.28,244.99,0.47,0.03,"3,416.69",115.80
2,3.00,0.15,0.15,210.01,0.88,0.01,"26,052.91",185.31,328.86,0.44,0.04,"3,812.81",143.16
3,4.00,0.10,0.10,271.06,0.62,0.01,"19,840.72",168.05,394.50,0.39,0.04,"3,875.93",154.16

In [ ]:
stuff_to_analyze

['modlyr',
 'collsymb',
 'perslimbi',
 'acclimbi',
 'deductiblecol',
 'pol_eff_date',
 'pol_exp_date',
 'pol_eff_year',
 'DrvAge',
 'DrvSex',
 'DrvMarSts',
 'color_exterior',
 'color_interior',
 'year_CEF',
 'mDrvGenMarSts',
 'modelyear',
 'rand',
 'zip',
 'pol_id',
 'vin_id']

In [ ]:
eda_table(data1,'modlyr')

,modlyr,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,"1,949.00",0.00,0.00,28.27,0.00,0.00,NaN,0.00,18.18,0.00,0.00,NaN,0.00
1,"1,952.00",0.00,0.00,95.86,0.00,0.00,NaN,0.00,63.57,0.00,0.00,NaN,0.00
2,"1,964.00",0.00,0.00,39.89,0.00,0.00,NaN,0.00,49.86,0.00,0.00,NaN,0.00
3,"1,965.00",0.00,0.00,68.25,0.00,0.00,NaN,0.00,33.21,0.00,0.00,NaN,0.00
4,"1,967.00",0.00,0.00,29.14,0.00,0.00,NaN,0.00,76.44,0.00,0.00,NaN,0.00
5,"1,968.00",0.00,0.00,37.01,0.00,0.00,NaN,0.00,13.00,0.00,0.00,NaN,0.00
6,"1,969.00",0.00,0.00,40.43,0.00,0.00,NaN,0.00,82.82,0.00,0.00,NaN,0.00
7,"1,971.00",0.00,0.00,82.69,0.00,0.00,NaN,0.00,55.13,0.00,0.00,NaN,0.00
8,"1,973.00",0.00,0.00,55.14,0.00,0.00,NaN,0.00,46.37,0.00,0.00,NaN,0.00
9,"1,974.00",0.00,0.00,130.91,0.00,0.00,NaN,0.00,87.89,0.00,0.00,NaN,0.00
10,"1,976.00",0.00,0.00,69.43,0.00,0.00,NaN,0.00,51.58,0.00,0.00,NaN,0.00
11,"1,977.00",0.00,0.00,99.18,0.00,0.00,NaN,0.00,23.80,0.00,0.00,NaN,0.00
12,"1,978.00",0.00,0.00,100.01,0.00,0.00,NaN,0.00,38.00,0.00,0.00,NaN,0.00
13,"1,979.00",0.00,0.00,247.18,0.00,0.00,NaN,0.00,182.87,0.00,0.00,NaN,0.00
14,"1,981.00",0.00,0.00,59.80,0.00,0.00,NaN,0.00,20.80,0.00,0.00,NaN,0.00
15,"1,982.00",0.00,0.00,71.70,0.00,0.00,NaN,0.00,143.39,0.00,0.00,NaN,0.00
16,"1,983.00",0.00,0.00,62.16,0.00,0.00,NaN,0.00,49.21,0.00,0.00,NaN,0.00
17,"1,984.00",0.00,0.00,86.95,0.00,0.00,NaN,0.00,63.47,0.00,0.00,NaN,0.00
18,"1,985.00",0.00,0.00,34.77,0.00,0.00,NaN,0.00,78.18,0.00,0.00,NaN,0.00
19,"1,986.00",0.00,0.00,119.39,0.00,0.00,NaN,0.00,96.45,0.00,0.00,NaN,0.00
20,"1,987.00",0.00,0.00,77.50,0.00,0.00,NaN,0.00,41.52,0.00,0.00,NaN,0.00
21,"1,988.00",0.00,0.00,135.63,0.00,0.00,NaN,0.00,92.41,0.00,0.00,NaN,0.00
22,"1,989.00",0.00,0.00,74.64,0.00,0.00,NaN,0.00,48.65,0.00,0.00,NaN,0.00
23,"1,990.00",0.00,0.00,81.42,0.00,0.00,NaN,0.00,92.76,0.00,0.00,NaN,0.00
24,"1,991.00",0.00,0.00,97.43,0.00,0.00,NaN,0.00,100.42,0.00,0.00,NaN,0.00
25,"1,992.00",0.00,0.00,102.82,0.00,0.00,NaN,0.00,96.01,0.00,0.00,NaN,0.00
26,"1,993.00",0.00,0.00,97.15,0.00,0.00,NaN,0.00,145.72,0.00,0.00,NaN,0.00
27,"1,994.00",0.00,0.00,86.16,0.00,0.00,NaN,0.00,111.05,0.00,0.00,NaN,0.00
28,"1,995.00",0.00,0.00,105.38,0.00,0.00,NaN,0.00,112.45,0.00,0.00,NaN,0.00
29,"1,996.00",0.00,0.00,108.97,0.00,0.00,NaN,0.00,117.88,0.00,0.00,NaN,0.00
30,"1,997.00",0.00,0.00,96.31,1.20,0.01,"9,000.00",115.17,103.25,0.00,0.00,NaN,0.00
31,"1,998.00",0.00,0.00,109.85,0.00,0.00,NaN,0.00,132.39,0.16,0.01,"2,256.98",20.68
32,"1,999.00",0.00,0.00,108.39,0.00,0.00,NaN,0.00,124.99,0.05,0.01,525.87,6.54
33,"2,000.00",0.00,0.00,108.07,0.00,0.00,NaN,0.00,130.88,0.53,0.02,"2,918.46",69.64
34,"2,001.00",0.01,0.01,114.95,0.43,0.01,"7,129.30",49.11,146.56,0.49,0.03,"2,322.67",71.99
35,"2,002.00",0.01,0.01,125.36,1.57,0.01,"38,347.03",196.51,165.43,0.65,0.04,"2,994.31",107.41
36,"2,003.00",0.01,0.01,124.59,0.00,0.00,NaN,0.00,155.33,0.45,0.03,"2,529.38",69.20
37,"2,004.00",0.01,0.01,129.96,0.39,0.01,"5,525.34",51.21,172.95,0.64,0.03,"3,524.23",111.05
38,"2,005.00",0.01,0.01,123.78,0.60,0.01,"8,323.22",74.04,170.24,0.50,0.03,"2,865.31",84.97
39,"2,006.00",0.01,0.01,132.05,0.33,0.01,"5,946.64",43.74,198.38,0.72,0.03,"4,212.91",142.53
40,"2,007.00",0.01,0.01,131.96,1.40,0.01,"15,154.60",184.89,200.96,0.56,0.04,"3,086.33",112.96
41,"2,008.00",0.01,0.01,133.31,0.89,0.01,"10,368.67",118.32,215.32,0.81,0.04,"4,557.35",173.36
42,"2,009.00",0.01,0.01,124.86,0.05,0.00,"3,000.00",6.03,225.72,0.40,0.02,"3,718.27",89.68
43,"2,010.00",0.01,0.01,123.64,0.24,0.01,"3,935.28",30.08,232.59,0.65,0.03,"4,739.11",152.15
44,"2,011.00",0.01,0.01,120.47,0.65,0.00,"19,483.33",78.61,229.37,0.33,0.03,"2,697.65",76.19
45,"2,012.00",0.01,0.01,123.27,0.31,0.01,"7,017.43",38.58,266.26,0.64,0.04,"3,894.59",171.28
46,"2,013.00",0.01,0.01,118.27,0.82,0.01,"19,105.25",96.91,266.66,0.54,0.04,"3,326.61",143.43
47,"2,014.00",0.01,0.01,115.91,0.21,0.00,"6,720.33",24.14,276.28,0.49,0.03,"4,352.09",135.50
48,"2,015.00",0.01,0.01,111.60,0.33,0.01,"7,245.82",37.32,271.31,0.55,0.05,"3,336.40",150.35
49,"2,016.00",0.01,0.01,111.70,0.01,0.00,750.00,1.33,273.41,0.63,0.04,"4,022.92",171.42
50,"2,017.00",0.01,0.01,116.58,0.72,0.01,"14,363.33",83.67,301.36,0.52,0.03,"4,462.96",155.99
51,"2,018.00",0.00,0.00,102.56,0.00,0.00,NaN,0.00,256.83,0.65,0.03,"5,152.29",166.31
52,"2,019.00",0.00,0.00,66.61,0.00,0.00,NaN,0.00,160.92,0.00,0.00,NaN,0.00
53,NaN,0.79,0.79,187.59,0.59,0.01,"18,466.38",109.89,301.97,0.47,0.04,"3,755.07",142.61

### Looks like this field isn't well populated. Let's see if 'modelyear is better

In [ ]:
eda_table(data1,'modelyear')

,modelyear,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,"1,949.00",0.00,0.00,28.27,0.00,0.00,NaN,0.00,18.18,0.00,0.00,NaN,0.00
1,"1,952.00",0.00,0.00,95.86,0.00,0.00,NaN,0.00,63.57,0.00,0.00,NaN,0.00
2,"1,964.00",0.00,0.00,39.89,0.00,0.00,NaN,0.00,49.86,0.00,0.00,NaN,0.00
3,"1,965.00",0.00,0.00,68.25,0.00,0.00,NaN,0.00,33.21,0.00,0.00,NaN,0.00
4,"1,967.00",0.00,0.00,29.14,0.00,0.00,NaN,0.00,76.44,0.00,0.00,NaN,0.00
5,"1,968.00",0.00,0.00,37.01,0.00,0.00,NaN,0.00,13.00,0.00,0.00,NaN,0.00
6,"1,969.00",0.00,0.00,40.43,0.00,0.00,NaN,0.00,82.82,0.00,0.00,NaN,0.00
7,"1,971.00",0.00,0.00,82.69,0.00,0.00,NaN,0.00,55.13,0.00,0.00,NaN,0.00
8,"1,973.00",0.00,0.00,55.14,0.00,0.00,NaN,0.00,46.37,0.00,0.00,NaN,0.00
9,"1,974.00",0.00,0.00,130.91,0.00,0.00,NaN,0.00,87.89,0.00,0.00,NaN,0.00
10,"1,976.00",0.00,0.00,69.43,0.00,0.00,NaN,0.00,51.58,0.00,0.00,NaN,0.00
11,"1,977.00",0.00,0.00,99.18,0.00,0.00,NaN,0.00,23.80,0.00,0.00,NaN,0.00
12,"1,978.00",0.00,0.00,100.01,0.00,0.00,NaN,0.00,38.00,0.00,0.00,NaN,0.00
13,"1,979.00",0.00,0.00,247.18,0.00,0.00,NaN,0.00,182.87,0.00,0.00,NaN,0.00
14,"1,981.00",0.00,0.00,76.58,0.00,0.00,NaN,0.00,18.99,0.00,0.00,NaN,0.00
15,"1,982.00",0.00,0.00,124.37,0.00,0.00,NaN,0.00,84.31,0.00,0.00,NaN,0.00
16,"1,983.00",0.00,0.00,70.38,0.00,0.00,NaN,0.00,29.90,0.00,0.00,NaN,0.00
17,"1,984.00",0.00,0.00,91.50,0.00,0.00,NaN,0.00,52.56,0.00,0.00,NaN,0.00
18,"1,985.00",0.00,0.00,74.28,0.00,0.00,NaN,0.00,60.28,0.00,0.00,NaN,0.00
19,"1,986.00",0.00,0.00,99.83,0.00,0.00,NaN,0.00,52.55,0.00,0.00,NaN,0.00
20,"1,987.00",0.00,0.00,155.98,0.00,0.00,NaN,0.00,59.07,0.00,0.00,NaN,0.00
21,"1,988.00",0.00,0.00,122.03,0.00,0.00,NaN,0.00,58.52,0.00,0.00,NaN,0.00
22,"1,989.00",0.00,0.00,99.30,0.07,0.03,245.70,6.78,69.19,0.00,0.00,NaN,0.00
23,"1,990.00",0.00,0.00,110.66,0.00,0.00,NaN,0.00,66.89,0.00,0.00,NaN,0.00
24,"1,991.00",0.00,0.00,110.73,0.00,0.00,NaN,0.00,75.88,0.62,0.02,"2,474.00",46.94
25,"1,992.00",0.00,0.00,140.49,0.00,0.00,NaN,0.00,84.79,0.30,0.02,"1,638.00",25.38
26,"1,993.00",0.00,0.00,124.55,0.00,0.00,NaN,0.00,92.98,0.33,0.01,"2,671.65",30.37
27,"1,994.00",0.00,0.00,115.98,0.00,0.00,NaN,0.00,90.24,0.24,0.01,"3,418.00",21.37
28,"1,995.00",0.00,0.00,156.63,0.00,0.00,NaN,0.00,115.15,0.03,0.01,306.77,3.04
29,"1,996.00",0.00,0.00,135.41,0.00,0.00,NaN,0.00,125.69,0.09,0.01,"1,215.36",11.19
30,"1,997.00",0.01,0.01,156.32,0.17,0.00,"9,000.00",26.06,138.12,0.09,0.01,"1,033.42",11.97
31,"1,998.00",0.01,0.01,159.06,0.13,0.00,"9,039.52",20.13,148.87,0.07,0.01,"1,194.63",10.64
32,"1,999.00",0.01,0.01,154.51,0.45,0.00,"15,021.02",68.88,153.70,0.15,0.01,"1,697.65",23.35
33,"2,000.00",0.02,0.02,164.23,0.25,0.00,"10,113.07",40.28,162.01,0.20,0.01,"2,447.04",31.68
34,"2,001.00",0.02,0.02,156.13,0.08,0.00,"7,129.30",12.89,181.64,0.30,0.03,"2,098.63",55.02
35,"2,002.00",0.03,0.03,171.80,0.92,0.01,"27,666.66",157.70,189.96,0.30,0.02,"2,286.24",56.47
36,"2,003.00",0.04,0.04,173.29,0.78,0.01,"25,158.93",135.73,193.18,0.42,0.03,"2,985.42",80.53
37,"2,004.00",0.04,0.04,179.93,0.65,0.01,"16,831.13",116.44,217.74,0.41,0.03,"2,655.92",88.43
38,"2,005.00",0.05,0.05,172.29,0.99,0.01,"22,780.90",170.41,220.12,0.36,0.03,"2,509.38",78.84
39,"2,006.00",0.05,0.05,181.06,0.38,0.01,"12,746.61",68.56,246.49,0.38,0.03,"3,162.23",94.12
40,"2,007.00",0.05,0.05,190.17,0.85,0.01,"15,376.50",160.97,258.61,0.47,0.04,"3,169.96",121.33
41,"2,008.00",0.06,0.06,181.55,0.36,0.01,"10,943.03",64.73,260.84,0.40,0.03,"3,115.85",104.14
42,"2,009.00",0.04,0.04,188.96,0.23,0.01,"7,514.78",44.12,281.40,0.45,0.04,"3,481.49",125.55
43,"2,010.00",0.05,0.05,187.25,0.34,0.00,"13,086.01",63.36,294.37,0.48,0.04,"3,935.99",140.21
44,"2,011.00",0.06,0.06,178.85,0.55,0.01,"17,728.69",97.52,287.21,0.39,0.04,"3,001.47",111.90
45,"2,012.00",0.06,0.06,181.76,0.35,0.01,"10,055.45",62.76,326.35,0.55,0.05,"3,518.19",180.66
46,"2,013.00",0.07,0.07,170.78,0.63,0.01,"17,533.57",107.55,322.60,0.58,0.05,"4,099.55",188.61
47,"2,014.00",0.08,0.08,178.45,0.32,0.01,"8,295.46",56.31,347.59,0.47,0.04,"3,862.25",162.72
48,"2,015.00",0.08,0.08,169.63,0.71,0.01,"19,960.32",119.61,358.31,0.69,0.04,"5,516.11",247.30
49,"2,016.00",0.06,0.06,169.11,1.61,0.00,"63,353.41",272.07,365.06,0.48,0.04,"4,187.43",176.23
50,"2,017.00",0.05,0.05,164.96,0.58,0.01,"13,194.31",96.37,373.14,0.60,0.05,"4,678.99",223.04
51,"2,018.00",0.03,0.03,157.23,0.35,0.01,"7,825.21",55.00,363.69,0.70,0.05,"4,713.33",252.97
52,"2,019.00",0.01,0.01,134.96,0.20,0.00,"7,141.67",26.94,323.57,0.29,0.03,"3,068.73",92.62
53,"2,020.00",0.00,0.00,76.58,0.00,0.00,NaN,0.00,210.56,1.17,0.03,"8,744.62",246.17
54,"2,021.00",0.00,0.00,12.23,0.00,0.00,NaN,0.00,39.09,0.00,0.00,NaN,0.00
55,NaN,0.01,0.01,183.90,0.19,0.00,"11,673.28",34.94,277.48,0.29,0.03,"3,112.81",79.20

### It is, so let's use that instead and get rid of modlyr.  
#### Hint: using del is another way to remove columns

In [ ]:
print(data1.shape)
del data1['modlyr']
stuff_to_analyze.remove('modlyr')
print(data1.shape)

(100443, 37)
(100443, 36)

### Model year isn't useful alone, let's see what the policy year looks like

In [ ]:
eda_table(data1,'pol_eff_year')

,pol_eff_year,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,2014,0.04,0.04,106.08,0.54,0.01,"8,375.68",57.28,202.03,0.58,0.04,"3,141.93",118.18
1,2015,0.20,0.20,159.65,0.77,0.01,"20,053.10",123.18,262.07,0.48,0.04,"3,284.56",125.66
2,2016,0.20,0.20,165.96,0.59,0.01,"17,395.65",98.09,284.80,0.47,0.04,"3,553.75",133.69
3,2017,0.20,0.20,175.37,0.77,0.01,"19,199.19",134.54,293.35,0.53,0.04,"4,181.90",155.06
4,2018,0.19,0.19,185.52,0.39,0.00,"15,361.34",72.70,295.41,0.43,0.04,"3,461.27",125.58
5,2019,0.17,0.17,202.21,0.36,0.01,"12,839.80",72.69,310.73,0.51,0.04,"4,466.45",157.44

In [ ]:
data1['veh_age'] = data1['pol_eff_year'] - data1['modelyear']

eda_table(data1,'veh_age')

,veh_age,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,-2.00,0.00,0.00,18.52,0.00,0.00,NaN,0.00,41.47,0.00,0.00,NaN,0.00
1,-1.00,0.02,0.02,76.71,6.47,0.01,"77,583.03",496.37,196.60,0.98,0.03,"6,006.51",192.15
2,0.00,0.07,0.07,145.89,0.95,0.01,"25,726.96",137.99,348.75,0.56,0.05,"4,145.75",196.79
3,1.00,0.08,0.08,171.67,0.13,0.00,"5,704.09",21.74,384.76,0.47,0.05,"3,917.11",181.75
4,2.00,0.08,0.08,169.36,0.87,0.01,"17,818.16",147.41,352.23,0.69,0.05,"4,982.44",244.07
5,3.00,0.07,0.07,171.47,0.49,0.01,"11,402.69",84.32,346.28,0.47,0.04,"3,848.26",164.31
6,4.00,0.07,0.07,178.74,0.38,0.01,"12,586.31",68.35,338.67,0.65,0.05,"4,615.68",219.61
7,5.00,0.06,0.06,182.00,0.67,0.01,"17,190.54",121.62,321.68,0.45,0.04,"3,542.31",143.35
8,6.00,0.06,0.06,182.46,0.30,0.01,"9,736.20",55.20,302.81,0.49,0.04,"3,925.56",148.37
9,7.00,0.06,0.06,182.38,0.28,0.00,"10,088.38",50.16,283.24,0.41,0.03,"3,462.08",117.27
10,8.00,0.06,0.06,186.03,0.25,0.01,"8,600.17",46.44,273.14,0.39,0.03,"3,057.05",105.85
11,9.00,0.05,0.05,190.16,0.46,0.01,"15,522.03",87.62,265.74,0.46,0.04,"2,980.14",121.71
12,10.00,0.05,0.05,184.37,0.71,0.01,"18,360.68",131.59,247.14,0.43,0.03,"3,278.86",107.43
13,11.00,0.05,0.05,184.96,1.03,0.01,"27,249.91",190.17,234.08,0.46,0.04,"3,033.86",107.98
14,12.00,0.04,0.04,183.19,0.65,0.01,"14,036.96",118.48,221.58,0.35,0.03,"2,564.73",77.31
15,13.00,0.04,0.04,186.86,0.93,0.01,"21,098.37",173.54,212.84,0.47,0.03,"2,939.52",99.40
16,14.00,0.03,0.03,178.41,0.54,0.01,"19,325.24",96.87,199.68,0.27,0.02,"2,377.36",54.29
17,15.00,0.03,0.03,171.53,0.12,0.00,"7,644.35",21.27,183.22,0.27,0.02,"2,586.28",48.58
18,16.00,0.02,0.02,169.01,0.75,0.01,"22,670.61",127.12,173.09,0.16,0.01,"2,080.66",27.22
19,17.00,0.01,0.01,165.63,0.19,0.00,"12,369.76",31.82,160.43,0.13,0.01,"1,568.11",20.17
20,18.00,0.01,0.01,165.22,0.03,0.00,"2,761.63",4.91,154.26,0.08,0.01,"1,112.31",11.86
21,19.00,0.01,0.01,168.96,0.13,0.00,"9,000.00",21.45,151.03,0.16,0.02,"1,454.24",24.26
22,20.00,0.00,0.00,155.02,0.00,0.00,NaN,0.00,134.73,0.14,0.01,"1,715.12",18.37
23,21.00,0.00,0.00,150.53,0.00,0.00,NaN,0.00,131.13,0.03,0.01,412.31,3.70
24,22.00,0.00,0.00,147.38,0.00,0.00,NaN,0.00,117.82,0.13,0.01,"2,671.65",15.76
25,23.00,0.00,0.00,132.19,0.00,0.00,NaN,0.00,95.78,0.32,0.02,"1,893.36",30.97
26,24.00,0.00,0.00,143.11,0.00,0.00,NaN,0.00,88.88,0.00,0.00,NaN,0.00
27,25.00,0.00,0.00,122.85,0.00,0.00,NaN,0.00,73.53,0.00,0.00,NaN,0.00
28,26.00,0.00,0.00,122.29,0.00,0.00,NaN,0.00,74.75,0.42,0.02,"1,638.00",31.72
29,27.00,0.00,0.00,120.75,0.05,0.03,245.70,6.22,71.14,0.88,0.03,"2,474.00",62.66
30,28.00,0.00,0.00,112.53,0.00,0.00,NaN,0.00,60.90,0.00,0.00,NaN,0.00
31,29.00,0.00,0.00,120.04,0.00,0.00,NaN,0.00,55.28,0.00,0.00,NaN,0.00
32,30.00,0.00,0.00,118.71,0.00,0.00,NaN,0.00,56.21,0.00,0.00,NaN,0.00
33,31.00,0.00,0.00,133.52,0.00,0.00,NaN,0.00,75.55,0.00,0.00,NaN,0.00
34,32.00,0.00,0.00,97.32,0.00,0.00,NaN,0.00,52.33,0.00,0.00,NaN,0.00
35,33.00,0.00,0.00,77.06,0.00,0.00,NaN,0.00,46.43,0.00,0.00,NaN,0.00
36,34.00,0.00,0.00,99.83,0.00,0.00,NaN,0.00,42.80,0.00,0.00,NaN,0.00
37,35.00,0.00,0.00,79.10,0.00,0.00,NaN,0.00,42.13,0.00,0.00,NaN,0.00
38,36.00,0.00,0.00,106.85,0.00,0.00,NaN,0.00,51.32,0.00,0.00,NaN,0.00
39,37.00,0.00,0.00,110.08,0.00,0.00,NaN,0.00,60.09,0.00,0.00,NaN,0.00
40,38.00,0.00,0.00,67.07,0.00,0.00,NaN,0.00,33.44,0.00,0.00,NaN,0.00
41,41.00,0.00,0.00,104.48,0.00,0.00,NaN,0.00,60.23,0.00,0.00,NaN,0.00
42,42.00,0.00,0.00,127.94,0.00,0.00,NaN,0.00,97.96,0.00,0.00,NaN,0.00
43,43.00,0.00,0.00,155.00,0.00,0.00,NaN,0.00,115.00,0.00,0.00,NaN,0.00
44,44.00,0.00,0.00,99.93,0.00,0.00,NaN,0.00,67.56,0.00,0.00,NaN,0.00
45,45.00,0.00,0.00,40.12,0.00,0.00,NaN,0.00,56.31,0.00,0.00,NaN,0.00
46,46.00,0.00,0.00,20.97,0.00,0.00,NaN,0.00,83.86,0.00,0.00,NaN,0.00
47,47.00,0.00,0.00,43.01,0.00,0.00,NaN,0.00,78.68,0.00,0.00,NaN,0.00
48,48.00,0.00,0.00,37.01,0.00,0.00,NaN,0.00,13.00,0.00,0.00,NaN,0.00
49,49.00,0.00,0.00,106.02,0.00,0.00,NaN,0.00,59.79,0.00,0.00,NaN,0.00
50,50.00,0.00,0.00,74.91,0.00,0.00,NaN,0.00,34.96,0.00,0.00,NaN,0.00
51,51.00,0.00,0.00,34.10,0.00,0.00,NaN,0.00,23.47,0.00,0.00,NaN,0.00
52,54.00,0.00,0.00,39.89,0.00,0.00,NaN,0.00,49.86,0.00,0.00,NaN,0.00
53,64.00,0.00,0.00,86.84,0.00,0.00,NaN,0.00,54.53,0.00,0.00,NaN,0.00
54,66.00,0.00,0.00,104.86,0.00,0.00,NaN,0.00,72.60,0.00,0.00,NaN,0.00
55,67.00,0.00,0.00,28.27,0.00,0.00,NaN,0.00,18.18,0.00,0.00,NaN,0.00
56,NaN,0.01,0.01,183.90,0.19,0.00,"11,673.28",34.94,277.48,0.29,0.03,"3,112.81",79.20

### Lets box this between 0 and 15 and fill the null value

In [ ]:
box_var(data1,'veh_age',0,15)

remove_list.append('modelyear')
# stuff_to_analyze.remove('modelyear')

fillna(data1, 'veh_age_box', 'veh_age_box') # generates an error - how do we trouble shoot this?

remove_list.append('veh_age')

eda_table(data1,'veh_age_box')

,veh_age_box,ee_bi_pct,ee_col_pct,avg_prem_bi,lr_bi,freq_bi,sev_bi,pp_bi,avg_prem_col,lr_col,freq_col,sev_col,pp_col
0,0.00,0.09,0.09,129.75,1.68,0.01,"39,171.13",218.43,313.16,0.62,0.04,"4,452.95",194.97
1,1.00,0.08,0.08,171.67,0.13,0.00,"5,704.09",21.74,384.76,0.47,0.05,"3,917.11",181.75
2,2.00,0.08,0.08,169.36,0.87,0.01,"17,818.16",147.41,352.23,0.69,0.05,"4,982.44",244.07
3,3.00,0.07,0.07,171.47,0.49,0.01,"11,402.69",84.32,346.28,0.47,0.04,"3,848.26",164.31
4,4.00,0.07,0.07,178.74,0.38,0.01,"12,586.31",68.35,338.67,0.65,0.05,"4,615.68",219.61
5,5.00,0.06,0.06,182.00,0.67,0.01,"17,190.54",121.62,321.68,0.45,0.04,"3,542.31",143.35
6,6.00,0.06,0.06,182.46,0.30,0.01,"9,736.20",55.20,302.81,0.49,0.04,"3,925.56",148.37
7,7.00,0.06,0.06,182.38,0.28,0.00,"10,088.38",50.16,283.24,0.41,0.03,"3,462.08",117.27
8,8.00,0.06,0.06,186.03,0.25,0.01,"8,600.17",46.44,273.14,0.39,0.03,"3,057.05",105.85
9,9.00,0.05,0.05,190.16,0.46,0.01,"15,522.03",87.62,265.74,0.46,0.04,"2,980.14",121.71
10,10.00,0.05,0.05,184.37,0.71,0.01,"18,360.68",131.59,247.14,0.43,0.03,"3,278.86",107.43
11,11.00,0.05,0.05,184.96,1.03,0.01,"27,249.91",190.17,234.08,0.46,0.04,"3,033.86",107.98
12,12.00,0.04,0.04,183.19,0.65,0.01,"14,036.96",118.48,221.58,0.35,0.03,"2,564.73",77.31
13,13.00,0.04,0.04,186.86,0.93,0.01,"21,098.37",173.54,212.84,0.47,0.03,"2,939.52",99.40
14,14.00,0.03,0.03,178.41,0.54,0.01,"19,325.24",96.87,199.68,0.27,0.02,"2,377.36",54.29
15,15.00,0.11,0.11,164.10,0.22,0.00,"13,334.97",36.63,167.92,0.19,0.01,"2,208.26",32.47

In [ ]:
stuff_to_analyze

# Group Work:
### The following creates a percentile of collision symbol by model year group.

In [ ]:
eda_table(data1,'collsymb')

In [ ]:
eda_table(data1,'modelyear')

### Collision Symbol varies by model year group
### Let's create the applicable model year groups and look at the data

In [ ]:
data1['my_group'] = '00: Unknown'
nxt = data1['modelyear'] < 9999
data1.loc[nxt,'my_group'] = '03: 2011+'
nxt = data1['modelyear'] <= 2010
data1.loc[nxt,'my_group'] = '02: 1990 to 2010'
nxt = data1['modelyear'] < 1990
data1.loc[nxt,'my_group'] = '01: <1990'

data1.groupby(['my_group','collsymb']).agg({'ee_col': 'sum'}).reset_index()

### In practice we would probably use the indicated ISO symbol factor from their filing
### For our purposes, let's create a percentile within each my_group and use that as a simple metric

In [ ]:
y = data1.groupby(['my_group','collsymb']).agg({'ee_col': 'sum'}).reset_index()
y['coll_symb_cumsum'] = y.groupby(['my_group']).ee_col.cumsum()
y

In [ ]:
z = y.groupby(['my_group']).agg({'ee_col': 'sum'}).reset_index()
z.rename(columns = {'ee_col': 'my_group_tot'}, inplace = True)

z

In [ ]:
y2 = y.merge(z, on = ['my_group'])

print(y.shape[0])
print(y2.shape[0])

y2

In [ ]:
y2['coll_symb_ntile'] = round(round(y2['coll_symb_cumsum']/y2['my_group_tot'],2)*100,0)

y2

In [ ]:
y3 = y2[(['my_group','collsymb','coll_symb_ntile'])].copy()

y3

# End of Group Work.
### Pick instruction up here

### Join this back to data1 - let's go ahead and overwrite data1 for our purposes but in practice you may create a new df called data2

In [ ]:
print(data1.shape)

data1 = data1.merge(y3, on = ['my_group','collsymb'], how = 'left')
# alt version
# data1 = data1.merge(y3, left_on = ['my_group','collsymb'], right_on = ['my_group','collsymb'], how = 'left')

print(data1.shape)

eda_table(data1,'coll_symb_ntile')

### We still have some null, so let's put that at 50

In [ ]:
fillna(data1,'coll_symb_ntile','coll_symb_ntile',specific_value = 50)
remove_list.append('my_group')
remove_list.append('collsymb')
stuff_to_analyze.remove('collsymb')

eda_table(data1,'coll_symb_ntile')

In [ ]:
stuff_to_analyze

In [ ]:
eda_table(data1,'perslimbi')

### Let's see if we need both per person and per occurrence limits

In [ ]:
data1.groupby(['perslimbi','acclimbi']).agg({'ee_bi': 'sum'}).reset_index()

### The only interesting situation is the 300/300 and 300/500
### Let's see if it will be worth keeping them separate

In [ ]:
eda_table(data1.loc[data1['perslimbi'] == 300000],'acclimbi')

# Group Work

### Lesson 2 Exercise 1
#### 1) create a new column 'limit_bi' by dividing 'perslimbi' by 1000 and rounding to the nearest integer
#### 2) fill NaN values using the fillna() function, allow default behavior
#### 3) limit the range to between 50 and 1000
#### 4) add 'perslimbi' and 'acclimbi' to remove_list
#### 5) remove 'perslimbi' and 'acclimbi' from stuff_to_analyze
#### 6) run eda_table function on 'limit_bi'

In [ ]:
# Solution goes here and in below cells

In [ ]:
stuff_to_analyze

In [ ]:
eda_table(data1,'deductiblecol')

### Based on this distribution, let's put everything under 350 into 250, 500 is alone, and 750 with 1000 and above

In [ ]:
data1['ded_coll'] = 250
nxt = data1['deductiblecol'] >= 500
data1.loc[nxt,'ded_coll'] = 500
nxt = data1['deductiblecol'] >= 750
data1.loc[nxt,'ded_coll'] = 1000

data1.groupby(['ded_coll','deductiblecol']).agg({'ee_col': 'sum'}).reset_index()

In [ ]:
remove_list.append('deductiblecol')
stuff_to_analyze.remove('deductiblecol')

In [ ]:
stuff_to_analyze

### We need pol_eff_date for a later merge but not pol_exp_date

In [ ]:
remove_list.append('pol_exp_date')

stuff_to_analyze.remove('pol_eff_date')
stuff_to_analyze.remove('pol_exp_date')

In [ ]:
stuff_to_analyze

In [ ]:
eda_table(data1,'pol_eff_year')

### Nothing to do here, let's keep going

In [ ]:
stuff_to_analyze.remove('pol_eff_year')

In [ ]:
stuff_to_analyze

In [ ]:
eda_table(data1,'DrvAge')

### Age 16 has no losses for BI, let's go with 17 as the bottom to keep this simple
### Age 80 seems like a reasonable point to end the range
### For the null value let's use the mean rounded to nearest whole number

In [ ]:
box_var(data1,'DrvAge',17,80,'DrvAge_box')

remove_list.append('DrvAge')
stuff_to_analyze.remove('DrvAge')

fillna(data1, 'DrvAge_box', 'DrvAge_box', specific_value = round(data1['DrvAge_box'].mean(),0))

eda_table(data1,'DrvAge_box')

In [ ]:
stuff_to_analyze

In [ ]:
eda_table(data1,'DrvSex')

### Let's make a flag for male

In [ ]:
data1['male'] = np.where(data1['DrvSex'] == 'M', True, False)

remove_list.append('DrvSex')
stuff_to_analyze.remove('DrvSex')

eda_table(data1,'male')

In [ ]:
stuff_to_analyze

In [ ]:
eda_table(data1,'DrvMarSts')

### Let's create flags for single and widowed

In [ ]:
data1['single'] = np.where(data1['DrvMarSts'] == 'S', True, False)
data1['widowed'] = np.where(data1['DrvMarSts'] == 'W', True, False)

remove_list.append('DrvMarSts')
stuff_to_analyze.remove('DrvMarSts')

eda_table(data1,'single')

In [ ]:
eda_table(data1,'widowed')

In [ ]:
stuff_to_analyze

In [ ]:
eda_table(data1,'color_exterior')

### Interesting to think about, but regulators don't accept color being used in rating, so let's remove these

In [ ]:
remove_list.append('color_exterior')
remove_list.append('color_interior')

stuff_to_analyze.remove('color_exterior')
stuff_to_analyze.remove('color_interior')

In [ ]:
stuff_to_analyze

### year_CEF is an internal only field - let's remove it

In [ ]:
remove_list.append('year_CEF')
stuff_to_analyze.remove('year_CEF')

In [ ]:
stuff_to_analyze

In [ ]:
eda_table(data1,'mDrvGenMarSts')

### This is a combination of gender and marital status; let's continue our treatment of each individually and remove this

In [ ]:
remove_list.append('mDrvGenMarSts')
stuff_to_analyze.remove('mDrvGenMarSts')

In [ ]:
stuff_to_analyze

### rand is an unneeded random number so let's remove it
### zip will be needed to merge data
### pol_id will be needed to make aggregated policy stats like max and min driver age
### vin_id will be needed to merge data

In [ ]:
remove_list.append('rand')
stuff_to_analyze.remove('rand')

## Create new dataframe as copy of original and remove unneeded fields

In [ ]:
remove_list

In [ ]:
[i for i in data1.columns if i not in remove_list and i not in facts]

In [ ]:
data2 = data1[([i for i in data1.columns if i not in remove_list])].copy()

print(data1.shape)
print(data2.shape)

## Minimize datatypes

### let's choose the minimum datatype to save memory
### first, look at dtypes

In [ ]:
data2.dtypes

### Now, what is the range of values for each of these?

In [ ]:
for i in [i for i in data2.columns]:
    print(i + ' min = ' + str(data2[i].min()) + ', max = ' + str(data2[i].max()))

### Which ones have decimal values?

In [ ]:
float_list = []
for i in [i for i in data2.columns]:
    a = data2[([i])].drop_duplicates()
    a['rounded'] = round(a[i],0)
    a['rounded_diff'] = np.where(a['rounded'] != a[i],1 ,0)
    b = a.loc[a['rounded_diff'] == 1]

    if b.shape[0] > 0:
        print(i)
        print(b.head())

        float_list.append(i)

### WHOOPS - there is a date in there which we can't round
### Let's try this again with some error handling

In [ ]:
float_list = []
for i in [i for i in data2.columns]:
    try:
        a = data2[([i])].drop_duplicates()
        a['rounded'] = round(a[i],0)
        a['rounded_diff'] = np.where(a['rounded'] != a[i],1 ,0)
        b = a.loc[a['rounded_diff'] == 1]

        if b.shape[0] > 0:
            print(i)
            print(b.head())

            float_list.append(i)
    except:
        pass

In [ ]:
float_list

### Since all minimums besides the float_list items are non-negative, we can use uint instead of int

### Max values by type:

##### uint8, uint16, uint32
##### 255,   65535, 4294967295

### Let's make lists of fields based on max value and minimum datatype

In [ ]:
remaining = [i for i in data2.columns if i not in float_list and i != 'pol_eff_date']
remaining

In [ ]:
uint8_list = []
uint16_list = []
uint32_list = []
error_list = []

for r in remaining:
    if data2[r].max() <= 255:
        uint8_list.append(r)
    elif (data2[r].max() <= 65535) & (data2[r].max() > 255):
        uint16_list.append(r)
    elif (data2[r].max() <= 4294967295) & (data2[r].max() > 65535):
        uint32_list.append(r)
    else:
        error_list.append(r)

print(uint8_list)
print(uint16_list)
print(uint32_list)
print(error_list)

### Make function to change datatype
### Only need to do float, unit8, and uin16 because uint32_list and error_list are empty
### Let's make a list of lists and the dtype we want to cast it to

In [ ]:
print('Before: ' + str(round(data2.memory_usage(deep=True).sum()/1024**3,3)))

def cast_dtyp(data,field,dtyp):
    data[field] = data[field].astype(dtyp)


mod_list = [float_list, uint8_list, uint16_list]
dtyp_list = ['float64','uint8','uint16']

for i, lst in enumerate(mod_list):
    for h in lst:
        cast_dtyp(data2,h,dtyp_list[i])

print('After: ' + str(round(data2.memory_usage(deep=True).sum()/1024**3,3)))

# Group Work:

## Merge CARFAX data & geodemographic data and check join quality

### let's see what we have in the carfax vehicle history data

In [ ]:
[i for i in cfax.columns]

### Year and LOO_days are not needed
### Let's analyze the rest after merging to determine if any others can be removed

In [ ]:
cfax_remove_list = ['Year', 'LOO_days']
for i in cfax_remove_list:
    del cfax[i]

### Now let's merge data2 and cfax, making sure the join is correct
### First, try inner join and check total records plus duplicates
### Before we do that, let's understand vin_id from data2

In [ ]:
print(data2.shape[0])
print(data2[(['vin_id'])].drop_duplicates().shape[0])

### So vin_id is repeated, which makes sense as we have multiple policy terms of the same vin
### Let's see if cfax data is distint

In [ ]:
print(cfax.shape[0])
print(cfax[(['vin_id'])].drop_duplicates().shape[0])

### It's not - let's see if pol_eff_date and Date will work

In [ ]:
print(data2.shape[0])
print(data2[(['pol_eff_date','vin_id'])].drop_duplicates().shape[0])

In [ ]:
print(cfax.shape[0])
print(cfax[(['Date','vin_id'])].drop_duplicates().shape[0])

### Looks like it will join properly, however inner join won't work because cfax data doesn't exist for every single set of keys
### Let's do a left join and clean up the dtypes and null values later

In [ ]:
cfax['Date'] = pd.to_datetime(cfax['Date'], infer_datetime_format = True)

print(data2.shape)

left_keys = ['pol_eff_date','vin_id']
right_keys = ['Date','vin_id']

data3 = data2.merge(cfax, left_on = left_keys, right_on = right_keys, how = 'left')

print(data3.shape)

### GREAT - we got a good join
### Did all 98,566 cfax records actually get into data3?
### Let's try this again in a way that allows us to figure that out

In [ ]:
cfax['cfax_join'] = 1

print(data2.shape)

left_keys = ['pol_eff_date','vin_id']
right_keys = ['Date','vin_id']

data3 = data2.merge(cfax, left_on = left_keys, right_on = right_keys, how = 'left')

print(data3.shape)

print(data3['cfax_join'].sum())

### YES, it worked
### We can delete that field

In [ ]:
del data3['cfax_join']

### Now to the geo data

In [ ]:
geo.head()

In [ ]:
[i for i in geo.columns]

### This is a ton of stuff
### Let's choose the best looking 4 for our purposes - in practice we would evaluate the signal on everything

In [ ]:
geo_keep = ['Zip','wtd_avg_travel_time','Education Attainment, High School (Pop 25+)_ntile_pct_pop25','Population Density_ntile','Employment; % unemployment_ntile']

geo_to_join = geo[(geo_keep)].copy()

print(geo_to_join.shape)
geo_to_join.head()

### Now we need to join it
### Let's see if we can make the key the exact same

In [ ]:
data3.head()

### We need to rename Zip to zip in geo_to_join
### Let's also rename these to shorter names

In [ ]:
geo_to_join.rename(columns = {
    'Zip': 'zip',
    'Education Attainment, High School (Pop 25+)_ntile_pct_pop25': 'diploma_ntile',
    'Population Density_ntile': 'pop_density_ntile',
    'Employment; % unemployment_ntile': 'unemployment_ntile'
}
                   , inplace = True)

geo_to_join.head()

### Same as before, let's evaluate the distinct zip counts

In [ ]:
print(data3[(['zip'])].drop_duplicates().shape[0])
print(geo_to_join[(['zip'])].drop_duplicates().shape[0])

### Oh, well that's obvious. data3 only contains data from Ohio, so of course we won't have the same counts
### Let's do an inner join and see how that works

In [ ]:
print(data3.shape)

data4 = data3.merge(geo_to_join, on = ['zip'])

print(data4.shape)

### Okay so it looks like a mismatch of datatypes.  Let's figure out what to change

In [ ]:
data3['zip'].dtypes

In [ ]:
geo_to_join['zip'].dtypes

### Let's fix it

In [ ]:
cast_dtyp(geo_to_join,'zip','uint16')

### Let's try the merge again

In [ ]:
print(data3.shape)

data4 = data3.merge(geo_to_join, on = ['zip'])

print(data4.shape)

### Inner join wasn't good enough because we have less records now
### No problem, we can left join and just like with cfax data fix the nulls later

In [ ]:
print(data3.shape)

data4 = data3.merge(geo_to_join, on = ['zip'], how = 'left')

print(data4.shape)

### We can now get rid of pol_eff_date

In [ ]:
del data4['pol_eff_date']

# Saving files - for reference

## Save as .csv, .pkl, .ftr and check space on disk + import time

### Feather is preferred for security, ability to read in R, performance

In [ ]:
save_path = ''

data4.to_csv(save_path + 'data4.csv', index = False)
data4.to_pickle(save_path + 'data4.pkl')
data4.to_feather(save_path + 'data4.ftr')

### Let's see how long each takes to import
### First, some basics on time measurements

In [ ]:
import time
from datetime import datetime

t1 = datetime.now()
time.sleep(1)
t2 = datetime.now()

print((t2 - t1).microseconds)

In [ ]:
t1 = datetime.now()
data4 = pd.read_csv(save_path + 'data4.csv')
t2 = datetime.now()

print('data4.csv: ' + str((t2 - t1).microseconds))

t1 = datetime.now()
data4 = pd.read_pickle(save_path + 'data4.pkl')
t2 = datetime.now()

print('data4.pkl: ' + str((t2 - t1).microseconds))

t1 = datetime.now()
data4 = pd.read_feather(save_path + 'data4.ftr')
t2 = datetime.now()

print('data4.ftr: ' + str((t2 - t1).microseconds))

### Let's see which versions maintained our dtypes upon import

In [ ]:
data4 = pd.read_csv(save_path + 'data4.csv')
data4.dtypes

In [ ]:
data4 = pd.read_pickle(save_path + 'data4.pkl')
data4.dtypes

In [ ]:
data4 = pd.read_feather(save_path + 'data4.ftr')
data4.dtypes

### Export to SQL and import from SQL
#### Make sure to specify schema = dbo to avoid the table ending up in your personal schema

In [ ]:
import sqlalchemy
import urllib

params = urllib.parse.quote_plus("DRIVER={SQL Server};SERVER=DOTD01P;DATABASE=bootcamp;Trusted_Connection=yes")
engine = sqlalchemy.create_engine("mssql+pyodbc:///?odbc_connect=%s" % params)
engine.connect()

data4.to_sql(name='data4', schema = 'dbo', con=engine, index = False, if_exists = 'replace')

In [ ]:
import pyodbc

conn = pyodbc.connect('''DRIVER={SQL Server};SERVER=DOTD01P;DATABASE=bootcamp;Trusted_Connection=yes''')
qry = '''select * from bootcamp.dbo.data4'''

t1 = datetime.now()
data4 = pd.read_sql(qry, conn)
t2 = datetime.now()

print('data4.sql: ' + str((t2 - t1).microseconds))

data4.dtypes